from __future__ import annotations

import json

import pytest
from sqlalchemy import create_engine, inspect, text

from app.db.session import init_db
from app.db.upgrades import upgrade_legacy_schema
from app.models.mcp_server import McpServer

AGENT_PLATFORM_TABLE_NAMES = {
    "agents",
    "mcp_servers",
    "model_connections",
    "output_schemas",
    "runs",
    "skills",
    "workflows",
}
LEGACY_BACKEND_TABLE_NAMES = {
    "agent_specs",
    "workflow_specs",
    "persona_profiles",
    "capability_registry_entries",
    "runtime_runs",
    "runtime_trace_events",
    "runtime_approvals",
    "runtime_checkpoints",
    "runtime_run_artifacts",
    "persona_projection_events",
    "orchestration_roles",
    "orchestration_characters",
}
_AGENT_PLATFORM_RESTART_FAILURE_MESSAGE = (
    "Run marked as failed during startup recovery because the previous process exited while "
    "it was still running."
)


def test_init_db_creates_agent_platform_tables_and_drops_legacy_backend_tables(
    database_url: str,
) -> None:
    init_db(database_url)
    engine = create_engine(database_url, future=True)

    try:
        table_names = set(inspect(engine).get_table_names())
        assert AGENT_PLATFORM_TABLE_NAMES <= table_names
        assert LEGACY_BACKEND_TABLE_NAMES.isdisjoint(table_names)
    finally:
        engine.dispose()


def test_init_db_running_run_recovery_marks_new_platform_runs_failed(database_url: str) -> None:
    init_db(database_url)
    engine = create_engine(database_url, future=True)

    try:
        with engine.begin() as connection:
            connection.exec_driver_sql(
                "INSERT INTO runs ("
                "target_kind, target_id, target_key, target_version, status, input, "
                "per_step_outputs"
                ") VALUES ('workflow', 1, 'stock_analysis', 1, 'running', '{}'::jsonb, '{}'::jsonb)"
            )

        init_db(database_url)

        with engine.connect() as connection:
            repaired_run = connection.exec_driver_sql(
                "SELECT status, error, finished_at IS NOT NULL FROM runs"
            ).one()

        assert repaired_run == ("failed", _AGENT_PLATFORM_RESTART_FAILURE_MESSAGE, True)
    finally:
        engine.dispose()


def test_init_db_repairs_legacy_run_identity_columns_to_target_columns(database_url: str) -> None:
    engine = create_engine(database_url, future=True)

    try:
        with engine.begin() as connection:
            connection.exec_driver_sql(
                """
                CREATE TABLE runs (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    workflow_id INTEGER NOT NULL,
                    workflow_key VARCHAR(120) NOT NULL,
                    workflow_version INTEGER NOT NULL,
                    input JSONB NOT NULL,
                    per_step_outputs JSONB NOT NULL DEFAULT '{}'::jsonb,
                    final_output JSONB,
                    status VARCHAR(20) NOT NULL DEFAULT 'running',
                    total_tokens INTEGER NOT NULL DEFAULT 0,
                    total_cost_usd NUMERIC(20, 8) NOT NULL DEFAULT 0,
                    trace_id VARCHAR(255),
                    error TEXT,
                    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    finished_at TIMESTAMPTZ,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    CONSTRAINT ck_runs_status CHECK (
                        status IN ('running', 'succeeded', 'failed')
                    ),
                    CONSTRAINT ck_runs_workflow_version_positive CHECK (workflow_version > 0),
                    CONSTRAINT ck_runs_total_tokens_non_negative CHECK (total_tokens >= 0),
                    CONSTRAINT ck_runs_total_cost_non_negative CHECK (total_cost_usd >= 0)
                )
                """
            )
            connection.exec_driver_sql(
                "CREATE INDEX ix_runs_workflow ON runs (workflow_id, workflow_version)"
            )
            connection.exec_driver_sql(
                "CREATE INDEX ix_runs_workflow_key ON runs (workflow_key, workflow_version)"
            )
            connection.exec_driver_sql(
                "INSERT INTO runs ("
                "workflow_id, workflow_key, workflow_version, input, per_step_outputs, "
                "final_output, status, total_tokens, total_cost_usd, trace_id"
                ") VALUES ("
                "7, 'market_review', 3, '{}'::jsonb, '{}'::jsonb, '{\"headline\":\"Buy\"}'::jsonb, "
                "'succeeded', 321, 0.15, 'trace-legacy-run'"
                ")"
            )

        init_db(database_url)
        init_db(database_url)

        run_columns = {column["name"]: column for column in inspect(engine).get_columns("runs")}
        run_indexes = {index["name"] for index in inspect(engine).get_indexes("runs")}
        run_constraints = {
            constraint["name"]
            for constraint in inspect(engine).get_check_constraints("runs")
            if constraint.get("name")
        }

        with engine.connect() as connection:
            migrated_run = connection.execute(
                text(
                    "SELECT target_kind, target_id, target_key, target_version, final_output "
                    "FROM runs WHERE trace_id = :trace_id"
                ),
                {"trace_id": "trace-legacy-run"},
            ).one()

        assert {"target_kind", "target_id", "target_key", "target_version"} <= set(run_columns)
        assert {"workflow_id", "workflow_key", "workflow_version"}.isdisjoint(run_columns)
        assert run_columns["target_kind"]["nullable"] is False
        assert run_columns["target_id"]["nullable"] is False
        assert run_columns["target_key"]["nullable"] is False
        assert run_columns["target_version"]["nullable"] is False
        assert {"ix_runs_status", "ix_runs_target", "ix_runs_target_key"} <= run_indexes
        assert {"ix_runs_workflow", "ix_runs_workflow_key"}.isdisjoint(run_indexes)
        assert {"ck_runs_target_kind", "ck_runs_target_version_positive"} <= run_constraints
        assert "ck_runs_workflow_version_positive" not in run_constraints
        assert migrated_run == ("workflow", 7, "market_review", 3, {"headline": "Buy"})
    finally:
        engine.dispose()


def test_init_db_rejects_conflicting_legacy_and_target_run_identity(database_url: str) -> None:
    engine = create_engine(database_url, future=True)

    try:
        with engine.begin() as connection:
            connection.exec_driver_sql(
                """
                CREATE TABLE runs (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    workflow_id INTEGER NOT NULL,
                    workflow_key VARCHAR(120) NOT NULL,
                    workflow_version INTEGER NOT NULL,
                    target_kind VARCHAR(20),
                    target_id INTEGER,
                    target_key VARCHAR(120),
                    target_version INTEGER,
                    input JSONB NOT NULL,
                    per_step_outputs JSONB NOT NULL DEFAULT '{}'::jsonb,
                    final_output JSONB,
                    status VARCHAR(20) NOT NULL DEFAULT 'running',
                    total_tokens INTEGER NOT NULL DEFAULT 0,
                    total_cost_usd NUMERIC(20, 8) NOT NULL DEFAULT 0,
                    trace_id VARCHAR(255),
                    error TEXT,
                    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    finished_at TIMESTAMPTZ,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    CONSTRAINT ck_runs_status CHECK (
                        status IN ('running', 'succeeded', 'failed')
                    ),
                    CONSTRAINT ck_runs_workflow_version_positive CHECK (workflow_version > 0),
                    CONSTRAINT ck_runs_total_tokens_non_negative CHECK (total_tokens >= 0),
                    CONSTRAINT ck_runs_total_cost_non_negative CHECK (total_cost_usd >= 0)
                )
                """
            )
            connection.exec_driver_sql(
                "INSERT INTO runs ("
                "workflow_id, workflow_key, workflow_version, target_kind, target_id, target_key, "
                "target_version, input, per_step_outputs, status"
                ") VALUES ("
                "7, 'market_review', 3, 'agent', 9, 'different_target', "
                "4, '{}'::jsonb, '{}'::jsonb, 'succeeded'"
                ")"
            )

        with pytest.raises(RuntimeError, match="Cannot auto-upgrade runs table"):
            init_db(database_url)
    finally:
        engine.dispose()


def test_init_db_fresh_schema_makes_agent_model_connection_id_non_null(database_url: str) -> None:
    init_db(database_url)
    engine = create_engine(database_url, future=True)

    try:
        agent_columns = {column["name"]: column for column in inspect(engine).get_columns("agents")}
        assert agent_columns["model_connection_id"]["nullable"] is False
    finally:
        engine.dispose()


def test_upgrade_legacy_schema_drops_preexisting_legacy_backend_tables(session_factory) -> None:
    with session_factory() as session:
        engine = session.get_bind()
        with engine.begin() as connection:
            connection.exec_driver_sql("CREATE TABLE IF NOT EXISTS agent_specs (id INTEGER)")
            connection.exec_driver_sql("CREATE TABLE IF NOT EXISTS workflow_specs (id INTEGER)")
            connection.exec_driver_sql("CREATE TABLE IF NOT EXISTS runtime_runs (id INTEGER)")
            connection.exec_driver_sql(
                "CREATE TABLE IF NOT EXISTS orchestration_roles (id INTEGER)"
            )
            connection.exec_driver_sql(
                "CREATE TABLE IF NOT EXISTS orchestration_characters (id INTEGER)"
            )

    upgrade_legacy_schema(engine)

    table_names = set(inspect(engine).get_table_names())
    assert LEGACY_BACKEND_TABLE_NAMES.isdisjoint(table_names)


def test_init_db_backfills_legacy_agent_models_into_placeholder_model_connections(
    database_url: str,
) -> None:
    engine = create_engine(database_url, future=True)

    try:
        with engine.begin() as connection:
            connection.exec_driver_sql(
                """
                CREATE TABLE agents (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    key VARCHAR(120) NOT NULL,
                    version INTEGER NOT NULL,
                    status VARCHAR(20) NOT NULL DEFAULT 'draft',
                    name VARCHAR(200) NOT NULL,
                    description TEXT NOT NULL DEFAULT '',
                    model VARCHAR(200) NOT NULL,
                    system_prompt TEXT NOT NULL,
                    input_schema JSONB NOT NULL,
                    output_schema_id INTEGER NOT NULL,
                    output_schema_version INTEGER NOT NULL,
                    skills JSONB NOT NULL DEFAULT '[]'::jsonb,
                    mcp_servers JSONB NOT NULL DEFAULT '[]'::jsonb,
                    budget_usd NUMERIC(20, 8) NOT NULL DEFAULT 0,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    CONSTRAINT ck_agents_status CHECK (
                        status IN ('draft', 'published', 'deprecated', 'archived')
                    ),
                    CONSTRAINT ck_agents_version_positive CHECK (version > 0),
                    CONSTRAINT ck_agents_output_schema_version_positive CHECK (
                        output_schema_version > 0
                    ),
                    CONSTRAINT ck_agents_budget_usd_non_negative CHECK (budget_usd >= 0),
                    CONSTRAINT uq_agents_key_version UNIQUE (key, version)
                )
                """
            )
            connection.execute(
                text(
                    "INSERT INTO agents ("
                    "key, version, status, name, description, model, system_prompt, input_schema, "
                    "output_schema_id, output_schema_version, skills, mcp_servers, budget_usd"
                    ") VALUES ("
                    ":key, :version, :status, :name, :description, :model, :system_prompt, "
                    "CAST(:input_schema AS jsonb), :output_schema_id, :output_schema_version, "
                    "CAST(:skills AS jsonb), CAST(:mcp_servers AS jsonb), :budget_usd"
                    ")"
                ),
                [
                    {
                        "key": "research_agent_alpha",
                        "version": 1,
                        "status": "published",
                        "name": "Research Agent Alpha",
                        "description": "Legacy agent row",
                        "model": "openai:gpt-5.4-mini",
                        "system_prompt": "Analyze the ticker.",
                        "input_schema": '{"type":"object"}',
                        "output_schema_id": 1,
                        "output_schema_version": 1,
                        "skills": "[]",
                        "mcp_servers": "[]",
                        "budget_usd": 0,
                    },
                    {
                        "key": "research_agent_beta",
                        "version": 1,
                        "status": "published",
                        "name": "Research Agent Beta",
                        "description": "Legacy agent row",
                        "model": "openai:gpt-5.4-mini",
                        "system_prompt": "Analyze the ticker.",
                        "input_schema": '{"type":"object"}',
                        "output_schema_id": 1,
                        "output_schema_version": 1,
                        "skills": "[]",
                        "mcp_servers": "[]",
                        "budget_usd": 0,
                    },
                    {
                        "key": "research_agent_gamma",
                        "version": 1,
                        "status": "draft",
                        "name": "Research Agent Gamma",
                        "description": "Legacy agent row",
                        "model": "openai:gpt-5.4",
                        "system_prompt": "Analyze the ticker.",
                        "input_schema": '{"type":"object"}',
                        "output_schema_id": 1,
                        "output_schema_version": 1,
                        "skills": "[]",
                        "mcp_servers": "[]",
                        "budget_usd": 0,
                    },
                ],
            )

        init_db(database_url)
        init_db(database_url)

        with engine.connect() as connection:
            placeholder_rows = connection.execute(
                text(
                    "SELECT name, model_id, base_url, reasoning_effort, "
                    "timeout_seconds, has_api_key "
                    "FROM model_connections ORDER BY model_id ASC"
                )
            ).all()
            linked_agents = connection.execute(
                text(
                    "SELECT a.key, a.model, a.model_connection_id, mc.model_id "
                    "FROM agents AS a "
                    "JOIN model_connections AS mc ON mc.id = a.model_connection_id "
                    "ORDER BY a.key ASC"
                )
            ).all()
            unresolved_agents = connection.execute(
                text("SELECT COUNT(*) FROM agents WHERE model_connection_id IS NULL")
            ).scalar_one()
            shared_placeholder_ids = connection.execute(
                text(
                    "SELECT COUNT(DISTINCT model_connection_id) "
                    "FROM agents WHERE model = 'openai:gpt-5.4-mini'"
                )
            ).scalar_one()

        repaired_agent_columns = {
            column["name"]: column for column in inspect(engine).get_columns("agents")
        }
        linked_agent_by_key = {row[0]: row for row in linked_agents}

        assert placeholder_rows == [
            (
                "openai:gpt-5.4",
                "openai:gpt-5.4",
                "https://api.openai.com/v1",
                "medium",
                60,
                False,
            ),
            (
                "openai:gpt-5.4-mini",
                "openai:gpt-5.4-mini",
                "https://api.openai.com/v1",
                "medium",
                60,
                False,
            ),
        ]
        assert unresolved_agents == 0
        assert linked_agent_by_key["research_agent_alpha"][1:] == (
            "openai:gpt-5.4-mini",
            linked_agent_by_key["research_agent_alpha"][2],
            "openai:gpt-5.4-mini",
        )
        assert linked_agent_by_key["research_agent_beta"][1:] == (
            "openai:gpt-5.4-mini",
            linked_agent_by_key["research_agent_alpha"][2],
            "openai:gpt-5.4-mini",
        )
        assert linked_agent_by_key["research_agent_gamma"][1:] == (
            "openai:gpt-5.4",
            linked_agent_by_key["research_agent_gamma"][2],
            "openai:gpt-5.4",
        )
        assert shared_placeholder_ids == 1
        assert repaired_agent_columns["model_connection_id"]["nullable"] is False
        assert {"temperature", "max_tool_rounds", "streaming"}.isdisjoint(
            repaired_agent_columns
        )
    finally:
        engine.dispose()


def test_upgrade_legacy_schema_repairs_existing_nullable_model_connection_column(
    database_url: str,
) -> None:
    init_db(database_url)
    engine = create_engine(database_url, future=True)

    try:
        with engine.begin() as connection:
            connection.exec_driver_sql(
                "ALTER TABLE agents ALTER COLUMN model_connection_id DROP NOT NULL"
            )
            connection.execute(
                text(
                    "INSERT INTO agents ("
                    "key, version, status, name, description, model_connection_id, model, "
                    "system_prompt, input_schema, output_schema_id, output_schema_version, skills, "
                    "mcp_servers, budget_usd"
                    ") VALUES ("
                    ":key, :version, :status, :name, :description, NULL, :model, "
                    ":system_prompt, CAST(:input_schema AS jsonb), :output_schema_id, "
                    ":output_schema_version, CAST(:skills AS jsonb), CAST(:mcp_servers AS jsonb), "
                    ":budget_usd"
                    ")"
                ),
                {
                    "key": "repair_nullable_agent",
                    "version": 1,
                    "status": "published",
                    "name": "Repair Nullable Agent",
                    "description": "Partial-upgrade agent row",
                    "model": "openai:gpt-5.4-mini",
                    "system_prompt": "Analyze the ticker.",
                    "input_schema": '{"type":"object"}',
                    "output_schema_id": 1,
                    "output_schema_version": 1,
                    "skills": "[]",
                    "mcp_servers": "[]",
                    "budget_usd": 0,
                },
            )

        init_db(database_url)

        with engine.connect() as connection:
            placeholder_count = connection.execute(
                text("SELECT COUNT(*) FROM model_connections WHERE model_id = :model_id"),
                {"model_id": "openai:gpt-5.4-mini"},
            ).scalar_one()
            linked_agent = connection.execute(
                text(
                    "SELECT model_connection_id IS NOT NULL "
                    "FROM agents WHERE key = :key AND version = 1"
                ),
                {"key": "repair_nullable_agent"},
            ).scalar_one()

        agent_columns = {column["name"]: column for column in inspect(engine).get_columns("agents")}
        assert placeholder_count == 1
        assert linked_agent is True
        assert agent_columns["model_connection_id"]["nullable"] is False
    finally:
        engine.dispose()


def test_upgrade_legacy_schema_rehardens_nullable_model_connection_column_when_already_linked(
    database_url: str,
) -> None:
    init_db(database_url)
    engine = create_engine(database_url, future=True)

    try:
        with engine.begin() as connection:
            linked_model_connection_id = connection.execute(
                text(
                    "INSERT INTO model_connections ("
                    "status, name, description, base_url, organization, project, model_id, "
                    "reasoning_effort, timeout_seconds, secret_payload, has_api_key, "
                    "created_at, updated_at"
                    ") VALUES ("
                    "'active', :name, '', 'https://api.openai.com/v1', NULL, NULL, :model_id, "
                    "'medium', 60, '{}'::jsonb, FALSE, NOW(), NOW()"
                    ") RETURNING id"
                ),
                {"name": "prelinked-connection", "model_id": "openai:gpt-5.4-mini"},
            ).scalar_one()
            connection.execute(
                text(
                    "INSERT INTO agents ("
                    "key, version, status, name, description, model_connection_id, model, "
                    "system_prompt, input_schema, output_schema_id, output_schema_version, skills, "
                    "mcp_servers, budget_usd"
                    ") VALUES ("
                    ":key, :version, :status, :name, :description, :model_connection_id, :model, "
                    ":system_prompt, CAST(:input_schema AS jsonb), :output_schema_id, "
                    ":output_schema_version, CAST(:skills AS jsonb), CAST(:mcp_servers AS jsonb), "
                    ":budget_usd"
                    ")"
                ),
                {
                    "key": "already_linked_agent",
                    "version": 1,
                    "status": "published",
                    "name": "Already Linked Agent",
                    "description": "Nullable-column no-backfill row",
                    "model_connection_id": linked_model_connection_id,
                    "model": "openai:gpt-5.4-mini",
                    "system_prompt": "Analyze the ticker.",
                    "input_schema": '{"type":"object"}',
                    "output_schema_id": 1,
                    "output_schema_version": 1,
                    "skills": "[]",
                    "mcp_servers": "[]",
                    "budget_usd": 0,
                },
            )
            connection.exec_driver_sql(
                "ALTER TABLE agents ALTER COLUMN model_connection_id DROP NOT NULL"
            )

        init_db(database_url)

        with engine.connect() as connection:
            linked_agent_id = connection.execute(
                text("SELECT model_connection_id FROM agents WHERE key = :key AND version = 1"),
                {"key": "already_linked_agent"},
            ).scalar_one()
            placeholder_count = connection.execute(
                text("SELECT COUNT(*) FROM model_connections WHERE model_id = :model_id"),
                {"model_id": "openai:gpt-5.4-mini"},
            ).scalar_one()

        agent_columns = {column["name"]: column for column in inspect(engine).get_columns("agents")}
        assert linked_agent_id == linked_model_connection_id
        assert placeholder_count == 1
        assert agent_columns["model_connection_id"]["nullable"] is False
    finally:
        engine.dispose()


def test_upgrade_legacy_schema_flattens_wrapped_mcp_rows(session_factory) -> None:
    flat_config = {
        "name": "Market Data",
        "description": "Published MCP server",
        "enabled": True,
        "transport": "http-sse",
        "url": "https://example.com/mcp",
        "headers": {"Authorization": "Bearer secret-token"},
    }

    with session_factory() as session:
        engine = session.get_bind()
        session.add(
            McpServer(
                key="market_data",
                version=1,
                status="draft",
                config={"mcpServers": {"market_data": flat_config}},
            )
        )
        session.commit()

    upgrade_legacy_schema(engine)

    with session_factory() as session:
        stored = session.query(McpServer).filter_by(key="market_data", version=1).one()
        assert stored.config == flat_config
        assert stored.flat_config == flat_config
        assert stored.transport == "http-sse"
        assert stored.enabled is True


def test_upgrade_legacy_schema_leaves_mismatched_wrapped_mcp_rows_unchanged(
    database_url: str,
) -> None:
    init_db(database_url)
    engine = create_engine(database_url, future=True)
    legacy_payload = {
        "mcpServers": {
            "other_key": {
                "name": "Market Data",
                "description": "Mismatched wrapper key",
                "enabled": True,
                "transport": "http-sse",
                "url": "https://example.com/mcp",
                "headers": {"Authorization": "Bearer secret-token"},
            }
        }
    }

    try:
        with engine.begin() as connection:
            connection.execute(
                text(
                    "INSERT INTO mcp_servers (key, version, status, config, created_at, "
                    "updated_at) "
                    "VALUES (:key, :version, :status, CAST(:config AS jsonb), NOW(), NOW())"
                ),
                {
                    "key": "market_data",
                    "version": 1,
                    "status": "draft",
                    "config": json.dumps(legacy_payload, sort_keys=True, separators=(",", ":")),
                },
            )

        upgrade_legacy_schema(engine)

        with engine.connect() as connection:
            stored = connection.execute(
                text("SELECT config FROM mcp_servers WHERE key = :key AND version = :version"),
                {"key": "market_data", "version": 1},
            ).scalar_one()

        assert stored == legacy_payload
    finally:
        engine.dispose()
