from __future__ import annotations

import json
import re
from dataclasses import dataclass

from sqlalchemy import bindparam, inspect, text
from sqlalchemy.engine import Connection, Engine

from app.db.validation import validate_supported_database_engine
from app.models.agent import (
    AGENT_MANIFEST_API_VERSION,
    AGENT_MANIFEST_COMPILER_VERSION,
    TEMPORARY_AGENT_MANIFEST_HASH,
    TEMPORARY_AGENT_MANIFEST_SOURCE,
)
from app.models.mcp_server import flatten_mcp_server_storage_payload
from app.models.workflow import TEMPORARY_WORKFLOW_MANIFEST_SOURCE, WORKFLOW_MANIFEST_API_VERSION

_OBSOLETE_TABLES = (
    "stock_analysis_versions",
    "stock_analysis_responses",
    "stock_analysis_requests",
    "stock_analysis_runs",
    "stock_analysis_conversations",
    "portfolio_stock_analysis_settings",
    "prompt_templates",
    "user_snippets",
    "llm_configs",
)
_LEGACY_BACKEND_TABLES = (
    "runtime_trace_events",
    "runtime_approvals",
    "runtime_checkpoints",
    "runtime_run_artifacts",
    "runtime_runs",
    "persona_projection_events",
    "capability_registry_entries",
    "persona_profiles",
    "workflow_specs",
    "agent_specs",
    "orchestration_characters",
    "orchestration_roles",
)
_LEGACY_SLUG_INVALID_CHARS_RE = re.compile(r"[^a-z0-9_]+")
_LEGACY_SLUG_DUPLICATE_UNDERSCORES_RE = re.compile(r"_+")
_MODEL_CONNECTION_KEY_INVALID_CHARS_RE = re.compile(r"[^a-z0-9_]+")
_MODEL_CONNECTION_KEY_DUPLICATE_UNDERSCORES_RE = re.compile(r"_+")
_MODEL_CONNECTION_KEY_MAX_LENGTH = 120
_AGENT_PLATFORM_RESTART_FAILURE_MESSAGE = (
    "Run marked as failed during startup recovery because the previous process exited while "
    "it was still running."
)
_RUN_TARGET_IDENTITY_CONFLICT_MESSAGE = (
    "Cannot auto-upgrade runs table because legacy workflow identity columns conflict with "
    "existing target identity values."
)
_CAPABILITY_STORAGE_CONFLICT_MESSAGE = (
    "Cannot auto-upgrade capability storage because legacy Skill storage and canonical "
    "Capability storage both contain data."
)
_MODEL_CONNECTION_PLACEHOLDER_BASE_URL = "https://api.openai.com/v1"
_MODEL_CONNECTION_PLACEHOLDER_REASONING_EFFORT = "medium"
_MODEL_CONNECTION_PLACEHOLDER_TIMEOUT_SECONDS = 60
_MODEL_CONNECTION_DEFAULT_API_STYLE = "responses"
_MODEL_CONNECTION_ALLOWED_API_STYLES = ("responses", "chat_completions")
_RETIRED_SKILL_TOOL_ID = "ledger.stock_analysis.report_lookup"
_REPAIRED_SKILL_TOOL_ID = "ledger.reports.lookup"


def _sql_string_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


_WORKFLOW_MANIFEST_API_VERSION_SQL = _sql_string_literal(WORKFLOW_MANIFEST_API_VERSION)
_TEMPORARY_WORKFLOW_MANIFEST_SOURCE_SQL = _sql_string_literal(TEMPORARY_WORKFLOW_MANIFEST_SOURCE)
_AGENT_MANIFEST_API_VERSION_SQL = _sql_string_literal(AGENT_MANIFEST_API_VERSION)
_TEMPORARY_AGENT_MANIFEST_SOURCE_SQL = _sql_string_literal(TEMPORARY_AGENT_MANIFEST_SOURCE)
_TEMPORARY_AGENT_MANIFEST_HASH_SQL = _sql_string_literal(TEMPORARY_AGENT_MANIFEST_HASH)
_AGENT_MANIFEST_COMPILER_VERSION_SQL = _sql_string_literal(AGENT_MANIFEST_COMPILER_VERSION)
_AGENT_PLATFORM_TABLE_STATEMENTS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "output_schemas",
        (
            """
            CREATE TABLE IF NOT EXISTS output_schemas (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                kind VARCHAR(20) NOT NULL DEFAULT 'standalone',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                json_schema JSONB NOT NULL,
                registry_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_output_schemas_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_output_schemas_kind CHECK (kind IN ('standalone', 'shared')),
                CONSTRAINT ck_output_schemas_version_positive CHECK (version > 0),
                CONSTRAINT uq_output_schemas_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_output_schemas_key ON output_schemas (key)",
            "CREATE INDEX IF NOT EXISTS ix_output_schemas_status ON output_schemas (status)",
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_output_schemas_published_key "
                "ON output_schemas (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_output_schemas_draft_key "
                "ON output_schemas (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "capabilities",
        (
            """
            CREATE TABLE IF NOT EXISTS capabilities (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                tool_grants JSONB NOT NULL DEFAULT '[]'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_capabilities_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_capabilities_version_positive CHECK (version > 0),
                CONSTRAINT uq_capabilities_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_capabilities_key ON capabilities (key)",
            "CREATE INDEX IF NOT EXISTS ix_capabilities_status ON capabilities (status)",
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_capabilities_published_key "
                "ON capabilities (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_capabilities_draft_key "
                "ON capabilities (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "mcp_servers",
        (
            """
            CREATE TABLE IF NOT EXISTS mcp_servers (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                config JSONB NOT NULL DEFAULT '{}'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_mcp_servers_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_mcp_servers_version_positive CHECK (version > 0),
                CONSTRAINT uq_mcp_servers_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_mcp_servers_key ON mcp_servers (key)",
            "CREATE INDEX IF NOT EXISTS ix_mcp_servers_status ON mcp_servers (status)",
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_mcp_servers_published_key "
                "ON mcp_servers (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_mcp_servers_draft_key "
                "ON mcp_servers (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "model_connections",
        (
            """
            CREATE TABLE IF NOT EXISTS model_connections (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'active',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                base_url VARCHAR(500) NOT NULL,
                organization VARCHAR(200),
                project VARCHAR(200),
                model_id VARCHAR(200) NOT NULL,
                reasoning_effort VARCHAR(20) NOT NULL DEFAULT 'medium',
                api_style VARCHAR(30) NOT NULL DEFAULT 'responses',
                timeout_seconds INTEGER NOT NULL DEFAULT 60,
                secret_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                has_api_key BOOLEAN NOT NULL DEFAULT FALSE,
                api_key_last4 VARCHAR(4),
                last_tested_at TIMESTAMPTZ,
                last_test_ok BOOLEAN,
                last_test_message TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_model_connections_status CHECK (
                    status IN ('active', 'archived')
                ),
                CONSTRAINT ck_model_connections_reasoning_effort CHECK (
                    reasoning_effort IN ('low', 'medium', 'high')
                ),
                CONSTRAINT ck_model_connections_api_style CHECK (
                    api_style IN ('responses', 'chat_completions')
                ),
                CONSTRAINT ck_model_connections_timeout_seconds_positive CHECK (
                    timeout_seconds > 0
                ),
                CONSTRAINT uq_model_connections_key UNIQUE (key)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_model_connections_status ON model_connections (status)",
            (
                "CREATE INDEX IF NOT EXISTS ix_model_connections_model_id "
                "ON model_connections (model_id)"
            ),
        ),
    ),
    (
        "agents",
        (
            """
            CREATE TABLE IF NOT EXISTS agents (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                manifest_api_version VARCHAR(80) NOT NULL DEFAULT 'ledger.agent/v1',
                manifest_source TEXT NOT NULL DEFAULT $$apiVersion: ledger.agent/v1
kind: Agent
metadata:
  source: legacy-payload-placeholder
$$,
                manifest_hash VARCHAR(64) NOT NULL DEFAULT
                    '98e17b8a6f1bd584aab673e2ab817f26173a7a1cd19ec5890c5bd2f0099c2f3b',
                compiler_version VARCHAR(80) NOT NULL DEFAULT 'agent-manifest-compiler/v1',
                model_connection_id INTEGER,
                model_connection_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
                model VARCHAR(200) NOT NULL,
                system_prompt TEXT NOT NULL,
                input_schema JSONB NOT NULL,
                output_schema_id INTEGER NOT NULL,
                output_schema_version INTEGER NOT NULL,
                capabilities JSONB NOT NULL DEFAULT '[]'::jsonb,
                mcp_servers JSONB NOT NULL DEFAULT '[]'::jsonb,
                budget_usd NUMERIC(20, 8) NOT NULL DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_agents_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_agents_version_positive CHECK (version > 0),
                CONSTRAINT ck_agents_output_schema_version_positive CHECK (
                    output_schema_version > 0
                ),
                CONSTRAINT ck_agents_budget_usd_non_negative CHECK (budget_usd >= 0),
                CONSTRAINT uq_agents_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_agents_key ON agents (key)",
            "CREATE INDEX IF NOT EXISTS ix_agents_status ON agents (status)",
            (
                "CREATE INDEX IF NOT EXISTS ix_agents_output_schema "
                "ON agents (output_schema_id, output_schema_version)"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_agents_published_key "
                "ON agents (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_agents_draft_key "
                "ON agents (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "workflows",
        (
            """
            CREATE TABLE IF NOT EXISTS workflows (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                manifest_api_version VARCHAR(80) NOT NULL DEFAULT 'ledger.workflow/v1',
                manifest_source TEXT NOT NULL DEFAULT $$apiVersion: ledger.workflow/v1
kind: Workflow
metadata:
  source: legacy-payload-placeholder
$$,
                input_schema JSONB NOT NULL,
                steps JSONB NOT NULL,
                output_spec JSONB NOT NULL,
                aggregate_budget_usd NUMERIC(20, 8) NOT NULL DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_workflows_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_workflows_version_positive CHECK (version > 0),
                CONSTRAINT ck_workflows_aggregate_budget_non_negative CHECK (
                    aggregate_budget_usd >= 0
                ),
                CONSTRAINT uq_workflows_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_workflows_key ON workflows (key)",
            "CREATE INDEX IF NOT EXISTS ix_workflows_status ON workflows (status)",
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_workflows_published_key "
                "ON workflows (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_workflows_draft_key "
                "ON workflows (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "runs",
        (
            """
            CREATE TABLE IF NOT EXISTS runs (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                target_kind VARCHAR(20) NOT NULL,
                target_id INTEGER NOT NULL,
                target_key VARCHAR(120) NOT NULL,
                target_version INTEGER NOT NULL,
                input JSONB NOT NULL,
                per_step_outputs JSONB NOT NULL DEFAULT '{}'::jsonb,
                final_output JSONB,
                status VARCHAR(20) NOT NULL DEFAULT 'running',
                total_tokens INTEGER NOT NULL DEFAULT 0,
                total_cost_usd NUMERIC(20, 8) NOT NULL DEFAULT 0,
                trace_id VARCHAR(255),
                error TEXT,
                started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                finished_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_runs_target_kind CHECK (target_kind IN ('agent', 'workflow')),
                CONSTRAINT ck_runs_status CHECK (status IN ('running', 'succeeded', 'failed')),
                CONSTRAINT ck_runs_target_version_positive CHECK (target_version > 0),
                CONSTRAINT ck_runs_total_tokens_non_negative CHECK (total_tokens >= 0),
                CONSTRAINT ck_runs_total_cost_non_negative CHECK (total_cost_usd >= 0)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_runs_status ON runs (status)",
            (
                "CREATE INDEX IF NOT EXISTS ix_runs_target "
                "ON runs (target_kind, target_id, target_version)"
            ),
            (
                "CREATE INDEX IF NOT EXISTS ix_runs_target_key "
                "ON runs (target_kind, target_key, target_version)"
            ),
        ),
    ),
)


def normalize_legacy_portfolio_slug(name: str) -> str:
    normalized = _LEGACY_SLUG_INVALID_CHARS_RE.sub("_", name.strip().lower())
    normalized = _LEGACY_SLUG_DUPLICATE_UNDERSCORES_RE.sub("_", normalized).strip("_")
    if not normalized:
        normalized = "portfolio"
    if not normalized[0].isalpha():
        normalized = f"portfolio_{normalized}"
    return normalized


def build_unique_legacy_portfolio_slug(base_slug: str, used_slugs: set[str]) -> str:
    suffix = ""
    sequence = 2

    while True:
        max_base_length = 100 - len(suffix)
        trimmed_base = base_slug[:max_base_length].rstrip("_")
        if not trimmed_base:
            trimmed_base = "portfolio"[:max_base_length].rstrip("_") or "p"

        candidate = f"{trimmed_base}{suffix}"
        if candidate not in used_slugs:
            used_slugs.add(candidate)
            return candidate

        suffix = f"_{sequence}"
        sequence += 1


def normalize_legacy_model_connection_key(
    *,
    name: str | None,
    model_id: str | None,
) -> str:
    for raw_value in (name, model_id, "model_connection"):
        if raw_value is None:
            continue
        normalized = _MODEL_CONNECTION_KEY_INVALID_CHARS_RE.sub(
            "_",
            str(raw_value).strip().lower(),
        )
        normalized = _MODEL_CONNECTION_KEY_DUPLICATE_UNDERSCORES_RE.sub(
            "_",
            normalized,
        ).strip("_")
        if normalized:
            break
    else:
        normalized = "model_connection"

    if not normalized[0].isalpha():
        normalized = f"model_connection_{normalized}"
    return normalized[:_MODEL_CONNECTION_KEY_MAX_LENGTH].rstrip("_") or "model_connection"


def build_unique_model_connection_key(base_key: str, used_keys: set[str]) -> str:
    suffix = ""
    sequence = 2

    while True:
        max_base_length = _MODEL_CONNECTION_KEY_MAX_LENGTH - len(suffix)
        trimmed_base = base_key[:max_base_length].rstrip("_")
        if not trimmed_base:
            trimmed_base = "model_connection"[:max_base_length].rstrip("_") or "m"

        candidate = f"{trimmed_base}{suffix}"
        if candidate not in used_keys:
            used_keys.add(candidate)
            return candidate

        suffix = f"_{sequence}"
        sequence += 1


@dataclass(frozen=True)
class _RetiredStockAnalysisSanitationTargets:
    portfolio_slugs: tuple[str, ...]
    template_names: tuple[str, ...]
    report_slugs: tuple[str, ...]
    output_schema_keys: tuple[str, ...]
    capability_keys: tuple[str, ...]
    mcp_server_keys: tuple[str, ...]
    agent_keys: tuple[str, ...]
    workflow_keys: tuple[str, ...]


def _load_retired_stock_analysis_sanitation_targets() -> _RetiredStockAnalysisSanitationTargets:
    from app import reset_seed

    return _RetiredStockAnalysisSanitationTargets(
        portfolio_slugs=(reset_seed.STARTER_PORTFOLIO_SLUG,),
        template_names=tuple(reset_seed.STARTER_TEMPLATE_NAMES),
        report_slugs=tuple(company["reportSlug"] for company in reset_seed.MAG7_COMPANIES),
        output_schema_keys=(
            reset_seed.STOCK_ANALYSIS_NOTE_SCHEMA_KEY,
            reset_seed.TRADING_DECISION_SCHEMA_KEY,
        ),
        capability_keys=(reset_seed.STOCK_ANALYSIS_CAPABILITY_KEY,),
        mcp_server_keys=(reset_seed.STOCK_ANALYSIS_MCP_SERVER_KEY,),
        agent_keys=reset_seed.STOCK_ANALYSIS_STEP_ONE_AGENT_KEYS
        + (reset_seed.STOCK_ANALYSIS_SYNTHESIZER_KEY,),
        workflow_keys=(reset_seed.STARTER_WORKFLOW_KEY,),
    )


def _delete_rows_by_column_values(
    connection: Connection,
    *,
    table_name: str,
    column_name: str,
    values: tuple[object, ...],
) -> None:
    if not values:
        return

    connection.execute(
        text(f'DELETE FROM "{table_name}" WHERE "{column_name}" IN :values').bindparams(
            bindparam("values", expanding=True)
        ),
        {"values": list(values)},
    )


def _select_ids_by_column_values(
    connection: Connection,
    *,
    table_name: str,
    match_column: str,
    values: tuple[object, ...],
) -> tuple[int, ...]:
    if not values:
        return ()

    return tuple(
        connection.execute(
            text(
                f'SELECT id FROM "{table_name}" WHERE "{match_column}" IN :values ORDER BY id'
            ).bindparams(bindparam("values", expanding=True)),
            {"values": list(values)},
        ).scalars()
    )


def _refresh_table_names(engine: Engine, table_names: set[str]) -> None:
    table_names.clear()
    table_names.update(inspect(engine).get_table_names())


def _cutover_capability_storage(engine: Engine, table_names: set[str]) -> None:
    _cutover_capability_table(engine, table_names)
    _refresh_table_names(engine, table_names)
    _cutover_agent_capability_refs(engine, table_names)
    _refresh_table_names(engine, table_names)


def _cutover_capability_table(engine: Engine, table_names: set[str]) -> None:
    has_legacy_table = "skills" in table_names
    has_canonical_table = "capabilities" in table_names
    if not has_legacy_table and not has_canonical_table:
        return

    with engine.begin() as connection:
        if has_legacy_table and has_canonical_table:
            legacy_count = connection.exec_driver_sql("SELECT COUNT(*) FROM skills").scalar_one()
            canonical_count = connection.exec_driver_sql(
                "SELECT COUNT(*) FROM capabilities"
            ).scalar_one()
            if legacy_count and canonical_count:
                raise RuntimeError(_CAPABILITY_STORAGE_CONFLICT_MESSAGE)
            if legacy_count:
                legacy_columns = {
                    column["name"] for column in inspect(connection).get_columns("skills")
                }
                source_column = (
                    "tool_grants" if "tool_grants" in legacy_columns else "tool_definitions"
                )
                connection.exec_driver_sql(
                    "INSERT INTO capabilities ("
                    "id, key, version, status, name, description, tool_grants, "
                    "created_at, updated_at"
                    ") SELECT id, key, version, status, name, description, "
                    f"{source_column}, created_at, updated_at FROM skills ORDER BY id"
                )
                connection.exec_driver_sql(
                    "SELECT setval(pg_get_serial_sequence('capabilities', 'id'), "
                    "COALESCE((SELECT MAX(id) FROM capabilities), 1), "
                    "(SELECT COUNT(*) > 0 FROM capabilities))"
                )
            connection.exec_driver_sql('DROP TABLE IF EXISTS "skills" CASCADE')
        elif has_legacy_table:
            connection.exec_driver_sql('ALTER TABLE "skills" RENAME TO "capabilities"')

    table_names.discard("skills")
    table_names.add("capabilities")
    _ensure_capability_tool_grants_column(engine, table_names)


def _ensure_capability_tool_grants_column(engine: Engine, table_names: set[str]) -> None:
    if "capabilities" not in table_names:
        return

    capability_columns = {column["name"] for column in inspect(engine).get_columns("capabilities")}
    with engine.begin() as connection:
        has_legacy_column = "tool_definitions" in capability_columns
        has_canonical_column = "tool_grants" in capability_columns
        if has_legacy_column and has_canonical_column:
            conflicts = connection.exec_driver_sql(
                "SELECT COUNT(*) FROM capabilities "
                "WHERE jsonb_typeof(tool_definitions) = 'array' "
                "AND tool_definitions <> '[]'::jsonb "
                "AND jsonb_typeof(tool_grants) = 'array' "
                "AND tool_grants <> '[]'::jsonb "
                "AND tool_grants <> tool_definitions"
            ).scalar_one()
            if conflicts:
                raise RuntimeError(_CAPABILITY_STORAGE_CONFLICT_MESSAGE)
            connection.exec_driver_sql(
                "UPDATE capabilities SET tool_grants = tool_definitions "
                "WHERE jsonb_typeof(tool_definitions) = 'array' "
                "AND tool_definitions <> '[]'::jsonb "
                "AND (jsonb_typeof(tool_grants) <> 'array' OR tool_grants = '[]'::jsonb)"
            )
            connection.exec_driver_sql("ALTER TABLE capabilities DROP COLUMN tool_definitions")
        elif has_legacy_column:
            connection.exec_driver_sql(
                "ALTER TABLE capabilities RENAME COLUMN tool_definitions TO tool_grants"
            )
        elif not has_canonical_column:
            connection.exec_driver_sql(
                "ALTER TABLE capabilities ADD COLUMN tool_grants JSONB NOT NULL DEFAULT '[]'::jsonb"
            )
        connection.exec_driver_sql(
            "ALTER TABLE capabilities ALTER COLUMN tool_grants SET DEFAULT '[]'::jsonb"
        )
        connection.exec_driver_sql(
            "UPDATE capabilities SET tool_grants = '[]'::jsonb WHERE tool_grants IS NULL"
        )
        connection.exec_driver_sql("ALTER TABLE capabilities ALTER COLUMN tool_grants SET NOT NULL")


def _legacy_agent_capabilities_expression(source_column: str) -> str:
    return f"""
    (
        SELECT COALESCE(
            jsonb_agg(
                CASE
                    WHEN jsonb_typeof(refs.ref) = 'object'
                    THEN (refs.ref - 'skillId' - 'skillKey' - 'skillVersion')
                        || CASE
                            WHEN refs.ref ? 'skillId'
                            THEN jsonb_build_object('capabilityId', refs.ref->'skillId')
                            ELSE '{{}}'::jsonb
                        END
                        || CASE
                            WHEN refs.ref ? 'skillKey'
                            THEN jsonb_build_object('capabilityKey', refs.ref->'skillKey')
                            ELSE '{{}}'::jsonb
                        END
                        || CASE
                            WHEN refs.ref ? 'skillVersion'
                            THEN jsonb_build_object('capabilityVersion', refs.ref->'skillVersion')
                            ELSE '{{}}'::jsonb
                        END
                    ELSE refs.ref
                END
                ORDER BY refs.ordinality
            ),
            '[]'::jsonb
        )
        FROM jsonb_array_elements(
            CASE
                WHEN jsonb_typeof(agents.{source_column}) = 'array'
                THEN agents.{source_column}
                ELSE '[]'::jsonb
            END
        ) WITH ORDINALITY AS refs(ref, ordinality)
    )
    """


def _cutover_agent_capability_refs(engine: Engine, table_names: set[str]) -> None:
    if "agents" not in table_names:
        return

    agent_columns = {column["name"] for column in inspect(engine).get_columns("agents")}
    with engine.begin() as connection:
        has_legacy_column = "skills" in agent_columns
        has_canonical_column = "capabilities" in agent_columns
        if has_legacy_column and has_canonical_column:
            conflicts = connection.exec_driver_sql(
                "SELECT COUNT(*) FROM agents "
                "WHERE jsonb_typeof(skills) = 'array' "
                "AND skills <> '[]'::jsonb "
                "AND jsonb_typeof(capabilities) = 'array' "
                "AND capabilities <> '[]'::jsonb"
            ).scalar_one()
            if conflicts:
                raise RuntimeError(_CAPABILITY_STORAGE_CONFLICT_MESSAGE)
            connection.exec_driver_sql(
                "UPDATE agents SET capabilities = "
                f"{_legacy_agent_capabilities_expression('skills')} "
                "WHERE jsonb_typeof(skills) = 'array' "
                "AND skills <> '[]'::jsonb "
                "AND (jsonb_typeof(capabilities) <> 'array' OR capabilities = '[]'::jsonb)"
            )
            connection.exec_driver_sql("ALTER TABLE agents DROP COLUMN skills")
        elif has_legacy_column:
            connection.exec_driver_sql('ALTER TABLE agents RENAME COLUMN "skills" TO capabilities')
            has_canonical_column = True
        elif not has_canonical_column:
            connection.exec_driver_sql(
                "ALTER TABLE agents ADD COLUMN capabilities JSONB NOT NULL DEFAULT '[]'::jsonb"
            )
            has_canonical_column = True

        if has_canonical_column:
            connection.exec_driver_sql(
                "UPDATE agents SET capabilities = "
                f"{_legacy_agent_capabilities_expression('capabilities')}"
            )
            connection.exec_driver_sql(
                "ALTER TABLE agents ALTER COLUMN capabilities SET DEFAULT '[]'::jsonb"
            )
            connection.exec_driver_sql(
                "UPDATE agents SET capabilities = '[]'::jsonb WHERE capabilities IS NULL"
            )
            connection.exec_driver_sql("ALTER TABLE agents ALTER COLUMN capabilities SET NOT NULL")


def _ensure_agent_platform_tables(engine: Engine, table_names: set[str]) -> None:
    with engine.begin() as connection:
        for table_name, statements in _AGENT_PLATFORM_TABLE_STATEMENTS:
            for statement in statements:
                connection.exec_driver_sql(statement)
            table_names.add(table_name)


def _ensure_model_connection_key_support(engine: Engine, table_names: set[str]) -> None:
    if "model_connections" not in table_names:
        return

    inspector = inspect(engine)
    model_connection_columns = {
        column["name"]: column for column in inspector.get_columns("model_connections")
    }
    model_connection_unique_constraints = {
        constraint["name"]
        for constraint in inspector.get_unique_constraints("model_connections")
        if constraint.get("name")
    }

    with engine.begin() as connection:
        if "key" not in model_connection_columns:
            connection.exec_driver_sql("ALTER TABLE model_connections ADD COLUMN key VARCHAR(120)")

        model_connection_rows = (
            connection.execute(
                text("SELECT id, key, name, model_id FROM model_connections ORDER BY id ASC")
            )
            .mappings()
            .all()
        )
        used_keys: set[str] = set()
        for row in model_connection_rows:
            raw_key = row["key"]
            raw_key_text = str(raw_key).strip() if raw_key is not None else ""
            base_key = normalize_legacy_model_connection_key(
                name=raw_key_text or row["name"],
                model_id=row["model_id"],
            )
            stable_key = build_unique_model_connection_key(base_key, used_keys)
            if raw_key_text != stable_key:
                connection.execute(
                    text(
                        "UPDATE model_connections "
                        "SET key = :key, updated_at = NOW() "
                        "WHERE id = :connection_id"
                    ),
                    {"key": stable_key, "connection_id": row["id"]},
                )

        connection.exec_driver_sql("ALTER TABLE model_connections ALTER COLUMN key SET NOT NULL")
        if "uq_model_connections_key" not in model_connection_unique_constraints:
            connection.exec_driver_sql(
                "ALTER TABLE model_connections ADD CONSTRAINT uq_model_connections_key UNIQUE (key)"
            )
        connection.exec_driver_sql(
            "CREATE INDEX IF NOT EXISTS ix_model_connections_key ON model_connections (key)"
        )


def _ensure_model_connection_api_style_support(engine: Engine, table_names: set[str]) -> None:
    if "model_connections" not in table_names:
        return

    inspector = inspect(engine)
    model_connection_columns = {
        column["name"]: column for column in inspector.get_columns("model_connections")
    }
    model_connection_check_constraints = {
        constraint["name"]
        for constraint in inspector.get_check_constraints("model_connections")
        if constraint.get("name")
    }

    with engine.begin() as connection:
        api_style_column = model_connection_columns.get("api_style")
        if api_style_column is None:
            _ = connection.exec_driver_sql(
                """
                ALTER TABLE model_connections
                ADD COLUMN api_style VARCHAR(30) NOT NULL DEFAULT 'responses'
                """
            )
        else:
            _ = connection.exec_driver_sql(
                "ALTER TABLE model_connections ALTER COLUMN api_style SET DEFAULT 'responses'"
            )

        _ = connection.execute(
            text(
                """
                UPDATE model_connections
                SET api_style = :default_api_style, updated_at = NOW()
                WHERE api_style IS NULL OR api_style NOT IN :allowed_api_styles
                """
            ).bindparams(bindparam("allowed_api_styles", expanding=True)),
            {
                "allowed_api_styles": _MODEL_CONNECTION_ALLOWED_API_STYLES,
                "default_api_style": _MODEL_CONNECTION_DEFAULT_API_STYLE,
            },
        )
        if api_style_column is None or api_style_column.get("nullable", True):
            _ = connection.exec_driver_sql(
                "ALTER TABLE model_connections ALTER COLUMN api_style SET NOT NULL"
            )
        if "ck_model_connections_api_style" not in model_connection_check_constraints:
            _ = connection.exec_driver_sql(
                """
                ALTER TABLE model_connections
                ADD CONSTRAINT ck_model_connections_api_style
                CHECK (api_style IN ('responses', 'chat_completions'))
                """
            )


def _ensure_agent_model_connection_support(engine: Engine, table_names: set[str]) -> None:
    if "agents" not in table_names:
        return

    inspector = inspect(engine)
    agent_columns = {column["name"] for column in inspector.get_columns("agents")}

    with engine.begin() as connection:
        if "model_connection_id" not in agent_columns:
            connection.exec_driver_sql("ALTER TABLE agents ADD COLUMN model_connection_id INTEGER")
        connection.exec_driver_sql(
            "CREATE INDEX IF NOT EXISTS ix_agents_model_connection ON agents (model_connection_id)"
        )


def _ensure_agent_model_connection_snapshot_support(engine: Engine, table_names: set[str]) -> None:
    if not {"agents", "model_connections"} <= table_names:
        return

    inspector = inspect(engine)
    agent_columns = {column["name"]: column for column in inspector.get_columns("agents")}
    model_connection_columns = {
        column["name"]: column for column in inspector.get_columns("model_connections")
    }
    api_style_snapshot_expression = (
        "CASE WHEN model_connection.api_style IN ('responses', 'chat_completions') "
        + "THEN model_connection.api_style ELSE 'responses' END"
        if "api_style" in model_connection_columns
        else "'responses'"
    )

    with engine.begin() as connection:
        if "model_connection_snapshot" not in agent_columns:
            connection.exec_driver_sql(
                "ALTER TABLE agents "
                "ADD COLUMN model_connection_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb"
            )

        _ = connection.execute(
            text(
                f"""
                UPDATE agents AS agent
                SET model_connection_snapshot = jsonb_build_object(
                        'base_url', model_connection.base_url,
                        'model_id', model_connection.model_id,
                        'organization', model_connection.organization,
                        'project', model_connection.project,
                        'reasoning_effort', model_connection.reasoning_effort,
                        'api_style', {api_style_snapshot_expression},
                        'timeout_seconds', model_connection.timeout_seconds
                    ),
                    updated_at = NOW()
                FROM model_connections AS model_connection
                WHERE agent.model_connection_id = model_connection.id
                  AND (
                    agent.model_connection_snapshot IS NULL
                    OR jsonb_typeof(agent.model_connection_snapshot) <> 'object'
                    OR agent.model_connection_snapshot = '{{}}'::jsonb
                    OR NOT (
                        agent.model_connection_snapshot ?& ARRAY[
                            'base_url',
                            'model_id',
                            'organization',
                            'project',
                            'reasoning_effort',
                            'api_style',
                            'timeout_seconds'
                        ]
                    )
                    OR COALESCE(agent.model_connection_snapshot->>'api_style', '') NOT IN (
                        'responses',
                        'chat_completions'
                    )
                  )
                """
            )
        )
        connection.exec_driver_sql(
            "ALTER TABLE agents " "ALTER COLUMN model_connection_snapshot SET DEFAULT '{}'::jsonb"
        )
        snapshot_column = agent_columns.get("model_connection_snapshot")
        if snapshot_column is None or snapshot_column.get("nullable", True):
            connection.exec_driver_sql(
                "ALTER TABLE agents ALTER COLUMN model_connection_snapshot SET NOT NULL"
            )


def _ensure_agent_manifest_columns(engine: Engine, table_names: set[str]) -> None:
    if "agents" not in table_names:
        return

    inspector = inspect(engine)
    agent_columns = {column["name"]: column for column in inspector.get_columns("agents")}

    with engine.begin() as connection:
        if "manifest_api_version" not in agent_columns:
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ADD COLUMN manifest_api_version VARCHAR(80)
                NOT NULL DEFAULT {_AGENT_MANIFEST_API_VERSION_SQL}
                """
            )
        else:
            _ = connection.execute(
                text(
                    """
                    UPDATE agents
                    SET manifest_api_version = :manifest_api_version
                    WHERE manifest_api_version IS NULL
                    """
                ),
                {"manifest_api_version": AGENT_MANIFEST_API_VERSION},
            )
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ALTER COLUMN manifest_api_version
                SET DEFAULT {_AGENT_MANIFEST_API_VERSION_SQL}
                """
            )
            if agent_columns["manifest_api_version"].get("nullable", True):
                _ = connection.exec_driver_sql(
                    "ALTER TABLE agents ALTER COLUMN manifest_api_version SET NOT NULL"
                )

        if "manifest_source" not in agent_columns:
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ADD COLUMN manifest_source TEXT
                NOT NULL DEFAULT {_TEMPORARY_AGENT_MANIFEST_SOURCE_SQL}
                """
            )
        else:
            _ = connection.execute(
                text(
                    """
                    UPDATE agents
                    SET manifest_source = :manifest_source
                    WHERE manifest_source IS NULL
                    """
                ),
                {"manifest_source": TEMPORARY_AGENT_MANIFEST_SOURCE},
            )
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ALTER COLUMN manifest_source
                SET DEFAULT {_TEMPORARY_AGENT_MANIFEST_SOURCE_SQL}
                """
            )
            if agent_columns["manifest_source"].get("nullable", True):
                _ = connection.exec_driver_sql(
                    "ALTER TABLE agents ALTER COLUMN manifest_source SET NOT NULL"
                )

        if "manifest_hash" not in agent_columns:
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ADD COLUMN manifest_hash VARCHAR(64)
                NOT NULL DEFAULT {_TEMPORARY_AGENT_MANIFEST_HASH_SQL}
                """
            )
        else:
            _ = connection.execute(
                text(
                    """
                    UPDATE agents
                    SET manifest_hash = :manifest_hash
                    WHERE manifest_hash IS NULL
                    """
                ),
                {"manifest_hash": TEMPORARY_AGENT_MANIFEST_HASH},
            )
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ALTER COLUMN manifest_hash
                SET DEFAULT {_TEMPORARY_AGENT_MANIFEST_HASH_SQL}
                """
            )
            if agent_columns["manifest_hash"].get("nullable", True):
                _ = connection.exec_driver_sql(
                    "ALTER TABLE agents ALTER COLUMN manifest_hash SET NOT NULL"
                )

        if "compiler_version" not in agent_columns:
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ADD COLUMN compiler_version VARCHAR(80)
                NOT NULL DEFAULT {_AGENT_MANIFEST_COMPILER_VERSION_SQL}
                """
            )
        else:
            _ = connection.execute(
                text(
                    """
                    UPDATE agents
                    SET compiler_version = :compiler_version
                    WHERE compiler_version IS NULL
                    """
                ),
                {"compiler_version": AGENT_MANIFEST_COMPILER_VERSION},
            )
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ALTER COLUMN compiler_version
                SET DEFAULT {_AGENT_MANIFEST_COMPILER_VERSION_SQL}
                """
            )
            if agent_columns["compiler_version"].get("nullable", True):
                _ = connection.exec_driver_sql(
                    "ALTER TABLE agents ALTER COLUMN compiler_version SET NOT NULL"
                )


def _ensure_workflow_manifest_columns(engine: Engine, table_names: set[str]) -> None:
    if "workflows" not in table_names:
        return

    inspector = inspect(engine)
    workflow_columns = {column["name"]: column for column in inspector.get_columns("workflows")}

    with engine.begin() as connection:
        if "manifest_api_version" not in workflow_columns:
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE workflows
                ADD COLUMN manifest_api_version VARCHAR(80)
                NOT NULL DEFAULT {_WORKFLOW_MANIFEST_API_VERSION_SQL}
                """
            )
        else:
            _ = connection.execute(
                text(
                    """
                    UPDATE workflows
                    SET manifest_api_version = :manifest_api_version
                    WHERE manifest_api_version IS NULL
                    """
                ),
                {"manifest_api_version": WORKFLOW_MANIFEST_API_VERSION},
            )
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE workflows
                ALTER COLUMN manifest_api_version
                SET DEFAULT {_WORKFLOW_MANIFEST_API_VERSION_SQL}
                """
            )
            if workflow_columns["manifest_api_version"].get("nullable", True):
                _ = connection.exec_driver_sql(
                    "ALTER TABLE workflows ALTER COLUMN manifest_api_version SET NOT NULL"
                )
        if "manifest_source" not in workflow_columns:
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE workflows
                ADD COLUMN manifest_source TEXT
                NOT NULL DEFAULT {_TEMPORARY_WORKFLOW_MANIFEST_SOURCE_SQL}
                """
            )
        else:
            _ = connection.execute(
                text(
                    """
                    UPDATE workflows
                    SET manifest_source = :manifest_source
                    WHERE manifest_source IS NULL
                    """
                ),
                {"manifest_source": TEMPORARY_WORKFLOW_MANIFEST_SOURCE},
            )
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE workflows
                ALTER COLUMN manifest_source
                SET DEFAULT {_TEMPORARY_WORKFLOW_MANIFEST_SOURCE_SQL}
                """
            )
            if workflow_columns["manifest_source"].get("nullable", True):
                _ = connection.exec_driver_sql(
                    "ALTER TABLE workflows ALTER COLUMN manifest_source SET NOT NULL"
                )


def _remove_dead_agent_runtime_fields(engine: Engine, table_names: set[str]) -> None:
    if "agents" not in table_names:
        return

    inspector = inspect(engine)
    agent_columns = {column["name"] for column in inspector.get_columns("agents")}

    with engine.begin() as connection:
        if "temperature" in agent_columns:
            connection.exec_driver_sql(
                "ALTER TABLE agents DROP COLUMN IF EXISTS temperature CASCADE"
            )
        if "max_tool_rounds" in agent_columns:
            connection.exec_driver_sql(
                "ALTER TABLE agents DROP COLUMN IF EXISTS max_tool_rounds CASCADE"
            )
        if "streaming" in agent_columns:
            connection.exec_driver_sql("ALTER TABLE agents DROP COLUMN IF EXISTS streaming CASCADE")


def _backfill_agent_model_connections(
    engine: Engine,
    table_names: set[str],
) -> None:
    if not {"agents", "model_connections"} <= table_names:
        return

    inspector = inspect(engine)
    agent_columns = {column["name"]: column for column in inspector.get_columns("agents")}
    if "model_connection_id" not in agent_columns or "model" not in agent_columns:
        return

    needs_non_null_enforcement = bool(agent_columns["model_connection_id"].get("nullable", True))

    with engine.begin() as connection:
        used_model_connection_keys = set(
            connection.execute(text("SELECT key FROM model_connections ORDER BY key ASC")).scalars()
        )
        unresolved_agent_count = connection.execute(
            text("SELECT COUNT(*) FROM agents WHERE model_connection_id IS NULL")
        ).scalar_one()
        if unresolved_agent_count == 0:
            if needs_non_null_enforcement:
                connection.exec_driver_sql(
                    "ALTER TABLE agents ALTER COLUMN model_connection_id SET NOT NULL"
                )
            return

        legacy_models = connection.execute(
            text(
                "SELECT DISTINCT BTRIM(model) AS model_id "
                "FROM agents "
                "WHERE model_connection_id IS NULL AND model IS NOT NULL AND BTRIM(model) <> '' "
                "ORDER BY model_id"
            )
        ).scalars()

        for legacy_model in legacy_models:
            placeholder_parameters = {
                "api_style": _MODEL_CONNECTION_DEFAULT_API_STYLE,
                "base_url": _MODEL_CONNECTION_PLACEHOLDER_BASE_URL,
                "model_id": legacy_model,
                "name": legacy_model,
                "reasoning_effort": _MODEL_CONNECTION_PLACEHOLDER_REASONING_EFFORT,
                "timeout_seconds": _MODEL_CONNECTION_PLACEHOLDER_TIMEOUT_SECONDS,
            }
            placeholder_connection_id = connection.execute(
                text(
                    "SELECT id FROM model_connections "
                    "WHERE status = 'active' "
                    "AND name = :name "
                    "AND model_id = :model_id "
                    "AND base_url = :base_url "
                    "AND reasoning_effort = :reasoning_effort "
                    "AND api_style = :api_style "
                    "AND timeout_seconds = :timeout_seconds "
                    "AND has_api_key = FALSE "
                    "ORDER BY id LIMIT 1"
                ),
                placeholder_parameters,
            ).scalar_one_or_none()

            if placeholder_connection_id is None:
                placeholder_parameters["key"] = build_unique_model_connection_key(
                    normalize_legacy_model_connection_key(
                        name=legacy_model,
                        model_id=legacy_model,
                    ),
                    used_model_connection_keys,
                )
                placeholder_connection_id = connection.execute(
                    text(
                        "INSERT INTO model_connections ("
                        "key, status, name, description, base_url, organization, project, "
                        "model_id, "
                        "reasoning_effort, api_style, timeout_seconds, "
                        "secret_payload, has_api_key, created_at, updated_at"
                        ") VALUES ("
                        ":key, 'active', :name, '', :base_url, NULL, NULL, :model_id, "
                        ":reasoning_effort, :api_style, :timeout_seconds, '{}'::jsonb, FALSE, "
                        "NOW(), NOW()"
                        ") RETURNING id"
                    ),
                    placeholder_parameters,
                ).scalar_one()

            connection.execute(
                text(
                    "UPDATE agents "
                    "SET model_connection_id = :model_connection_id, updated_at = NOW() "
                    "WHERE model_connection_id IS NULL AND BTRIM(model) = :legacy_model"
                ),
                {
                    "legacy_model": legacy_model,
                    "model_connection_id": placeholder_connection_id,
                },
            )

        remaining_null_count = connection.execute(
            text("SELECT COUNT(*) FROM agents WHERE model_connection_id IS NULL")
        ).scalar_one()
        if needs_non_null_enforcement and remaining_null_count == 0:
            connection.exec_driver_sql(
                "ALTER TABLE agents ALTER COLUMN model_connection_id SET NOT NULL"
            )


def _recover_stale_agent_platform_runs(engine: Engine, table_names: set[str]) -> None:
    if "runs" not in table_names:
        return

    with engine.begin() as connection:
        connection.execute(
            text(
                """
                UPDATE runs
                SET status = 'failed',
                    error = COALESCE(NULLIF(error, ''), :restart_failure_message),
                    finished_at = COALESCE(finished_at, NOW()),
                    updated_at = NOW()
                WHERE status = 'running'
                """
            ),
            {"restart_failure_message": _AGENT_PLATFORM_RESTART_FAILURE_MESSAGE},
        )


def _ensure_run_target_identity_support(engine: Engine, table_names: set[str]) -> None:
    if "runs" not in table_names:
        return

    inspector = inspect(engine)
    run_columns = {column["name"] for column in inspector.get_columns("runs")}
    run_constraints = {
        constraint["name"]
        for constraint in inspector.get_check_constraints("runs")
        if constraint.get("name")
    }

    with engine.begin() as connection:
        if "target_kind" not in run_columns:
            connection.exec_driver_sql("ALTER TABLE runs ADD COLUMN target_kind VARCHAR(20)")

        has_workflow_id = "workflow_id" in run_columns
        has_workflow_key = "workflow_key" in run_columns
        has_workflow_version = "workflow_version" in run_columns
        has_target_id = "target_id" in run_columns
        has_target_key = "target_key" in run_columns
        has_target_version = "target_version" in run_columns
        has_target_kind = "target_kind" in run_columns

        if has_workflow_id and has_target_id:
            target_id_conflicts = connection.execute(
                text(
                    "SELECT COUNT(*) FROM runs "
                    "WHERE workflow_id IS NOT NULL AND target_id IS NOT NULL "
                    "AND workflow_id <> target_id"
                )
            ).scalar_one()
            if target_id_conflicts:
                raise RuntimeError(_RUN_TARGET_IDENTITY_CONFLICT_MESSAGE)

        if has_workflow_key and has_target_key:
            target_key_conflicts = connection.execute(
                text(
                    "SELECT COUNT(*) FROM runs "
                    "WHERE workflow_key IS NOT NULL AND target_key IS NOT NULL "
                    "AND workflow_key <> target_key"
                )
            ).scalar_one()
            if target_key_conflicts:
                raise RuntimeError(_RUN_TARGET_IDENTITY_CONFLICT_MESSAGE)

        if has_workflow_version and has_target_version:
            target_version_conflicts = connection.execute(
                text(
                    "SELECT COUNT(*) FROM runs "
                    "WHERE workflow_version IS NOT NULL AND target_version IS NOT NULL "
                    "AND workflow_version <> target_version"
                )
            ).scalar_one()
            if target_version_conflicts:
                raise RuntimeError(_RUN_TARGET_IDENTITY_CONFLICT_MESSAGE)

        if (
            has_workflow_id
            and has_target_id
            and has_workflow_key
            and has_target_key
            and has_workflow_version
            and has_target_version
            and has_target_kind
        ):
            target_kind_conflicts = connection.execute(
                text(
                    "SELECT COUNT(*) FROM runs "
                    "WHERE workflow_id IS NOT NULL AND workflow_key IS NOT NULL "
                    "AND workflow_version IS NOT NULL AND target_kind IS NOT NULL "
                    "AND BTRIM(target_kind) <> '' AND target_kind <> 'workflow'"
                )
            ).scalar_one()
            if target_kind_conflicts:
                raise RuntimeError(_RUN_TARGET_IDENTITY_CONFLICT_MESSAGE)

        if "workflow_id" in run_columns and "target_id" not in run_columns:
            connection.exec_driver_sql("ALTER TABLE runs RENAME COLUMN workflow_id TO target_id")
        elif "workflow_id" in run_columns and "target_id" in run_columns:
            connection.exec_driver_sql(
                "UPDATE runs SET target_id = workflow_id WHERE target_id IS NULL"
            )
            connection.exec_driver_sql("ALTER TABLE runs DROP COLUMN workflow_id")

        if "workflow_key" in run_columns and "target_key" not in run_columns:
            connection.exec_driver_sql("ALTER TABLE runs RENAME COLUMN workflow_key TO target_key")
        elif "workflow_key" in run_columns and "target_key" in run_columns:
            connection.exec_driver_sql(
                "UPDATE runs SET target_key = workflow_key WHERE target_key IS NULL"
            )
            connection.exec_driver_sql("ALTER TABLE runs DROP COLUMN workflow_key")

        if "workflow_version" in run_columns and "target_version" not in run_columns:
            connection.exec_driver_sql(
                "ALTER TABLE runs RENAME COLUMN workflow_version TO target_version"
            )
        elif "workflow_version" in run_columns and "target_version" in run_columns:
            connection.exec_driver_sql(
                "UPDATE runs SET target_version = workflow_version WHERE target_version IS NULL"
            )
            connection.exec_driver_sql("ALTER TABLE runs DROP COLUMN workflow_version")

        connection.exec_driver_sql(
            "UPDATE runs "
            "SET target_kind = 'workflow' "
            "WHERE target_kind IS NULL OR BTRIM(target_kind) = ''"
        )
        connection.exec_driver_sql("ALTER TABLE runs ALTER COLUMN target_kind SET NOT NULL")
        connection.exec_driver_sql("ALTER TABLE runs ALTER COLUMN target_id SET NOT NULL")
        connection.exec_driver_sql("ALTER TABLE runs ALTER COLUMN target_key SET NOT NULL")
        connection.exec_driver_sql("ALTER TABLE runs ALTER COLUMN target_version SET NOT NULL")

        connection.exec_driver_sql(
            "ALTER TABLE runs DROP CONSTRAINT IF EXISTS ck_runs_workflow_version_positive"
        )
        if "ck_runs_target_kind" not in run_constraints:
            connection.exec_driver_sql(
                "ALTER TABLE runs ADD CONSTRAINT ck_runs_target_kind "
                "CHECK (target_kind IN ('agent', 'workflow'))"
            )
        if "ck_runs_target_version_positive" not in run_constraints:
            connection.exec_driver_sql(
                "ALTER TABLE runs ADD CONSTRAINT ck_runs_target_version_positive "
                "CHECK (target_version > 0)"
            )

        connection.exec_driver_sql("DROP INDEX IF EXISTS ix_runs_workflow")
        connection.exec_driver_sql("DROP INDEX IF EXISTS ix_runs_workflow_key")
        connection.exec_driver_sql(
            "CREATE INDEX IF NOT EXISTS ix_runs_target "
            "ON runs (target_kind, target_id, target_version)"
        )
        connection.exec_driver_sql(
            "CREATE INDEX IF NOT EXISTS ix_runs_target_key "
            "ON runs (target_kind, target_key, target_version)"
        )


def _reset_legacy_mcp_server_table(engine: Engine, table_names: set[str]) -> None:
    if "mcp_servers" not in table_names:
        return

    inspector = inspect(engine)
    mcp_columns = {column["name"] for column in inspector.get_columns("mcp_servers")}
    expected_columns = {"id", "key", "version", "status", "config", "created_at", "updated_at"}
    if mcp_columns == expected_columns:
        return

    if "config" in mcp_columns and not (
        {"transport", "command", "url", "auth", "enabled"} & mcp_columns
    ):
        return

    statements = dict(_AGENT_PLATFORM_TABLE_STATEMENTS)["mcp_servers"]
    with engine.begin() as connection:
        connection.exec_driver_sql('DROP TABLE IF EXISTS "mcp_servers" CASCADE')
        for statement in statements:
            connection.exec_driver_sql(statement)
    table_names.add("mcp_servers")


def _flatten_legacy_mcp_server_rows(engine: Engine, table_names: set[str]) -> None:
    if "mcp_servers" not in table_names:
        return

    with engine.begin() as connection:
        legacy_rows = connection.exec_driver_sql(
            "SELECT id, key, config FROM mcp_servers ORDER BY id"
        ).all()
        for server_id, key, config in legacy_rows:
            flattened_payload = flatten_mcp_server_storage_payload(config, key=str(key))
            if flattened_payload is None:
                continue

            next_payload, changed = flattened_payload
            if not changed:
                continue

            connection.execute(
                text(
                    "UPDATE mcp_servers "
                    "SET config = CAST(:config AS jsonb), updated_at = NOW() "
                    "WHERE id = :server_id"
                ),
                {
                    "config": json.dumps(next_payload, sort_keys=True, separators=(",", ":")),
                    "server_id": server_id,
                },
            )


def _repair_retired_capability_tool_grants(engine: Engine, table_names: set[str]) -> None:
    if "capabilities" not in table_names:
        return

    inspector = inspect(engine)
    capability_columns = {column["name"] for column in inspector.get_columns("capabilities")}
    if "tool_grants" not in capability_columns:
        return

    with engine.begin() as connection:
        _ = connection.execute(
            text(
                """
                UPDATE capabilities
                SET tool_grants = repaired_tool_grants.tool_grants,
                    updated_at = NOW()
                FROM (
                    SELECT capability.id,
                           jsonb_agg(
                               CASE
                                    WHEN jsonb_typeof(grants.tool_grant) = 'object'
                                         AND grants.tool_grant->>'tool' = :retired_tool_id
                                    THEN jsonb_set(
                                        grants.tool_grant,
                                        '{tool}',
                                        to_jsonb(CAST(:replacement_tool_id AS text)),
                                        false
                                    )
                                    ELSE grants.tool_grant
                               END
                               ORDER BY grants.ordinality
                           ) AS tool_grants
                    FROM capabilities AS capability
                    JOIN LATERAL jsonb_array_elements(
                        CASE
                            WHEN jsonb_typeof(capability.tool_grants) = 'array'
                            THEN capability.tool_grants
                            ELSE '[]'::jsonb
                        END
                    ) WITH ORDINALITY AS grants(tool_grant, ordinality) ON TRUE
                    WHERE capability.tool_grants @> CAST(:retired_tool_filter AS jsonb)
                    GROUP BY capability.id
                ) AS repaired_tool_grants
                WHERE capabilities.id = repaired_tool_grants.id
                  AND capabilities.tool_grants @> CAST(:retired_tool_filter AS jsonb)
                """
            ),
            {
                "retired_tool_id": _RETIRED_SKILL_TOOL_ID,
                "replacement_tool_id": _REPAIRED_SKILL_TOOL_ID,
                "retired_tool_filter": json.dumps(
                    [{"tool": _RETIRED_SKILL_TOOL_ID}],
                    separators=(",", ":"),
                ),
            },
        )


def _repair_tradingagents_transition_output_schemas(engine: Engine, table_names: set[str]) -> None:
    if "output_schemas" not in table_names:
        return

    inspector = inspect(engine)
    output_schema_columns = {column["name"] for column in inspector.get_columns("output_schemas")}
    if "json_schema" not in output_schema_columns:
        return

    target_keys = (
        "tradingagents_investment_debate_transition",
        "tradingagents_risk_debate_transition",
    )

    with engine.begin() as connection:
        rows = connection.execute(
            text("SELECT id, json_schema FROM output_schemas WHERE key = ANY(:target_keys)"),
            {"target_keys": list(target_keys)},
        ).all()
        for schema_id, json_schema in rows:
            if not isinstance(json_schema, dict):
                continue

            raw_properties = json_schema.get("properties")
            properties = raw_properties if isinstance(raw_properties, dict) else {}
            next_state = properties.get("nextState")
            if not isinstance(next_state, dict):
                next_state = {"type": "object", "additionalProperties": False}

            repaired_schema = dict(json_schema)
            properties = dict(properties)
            properties["nextState"] = next_state
            properties.pop("priorState", None)
            repaired_schema["properties"] = properties
            repaired_schema["required"] = ["nextState"]
            repaired_schema["additionalProperties"] = False
            repaired_schema["type"] = "object"

            if repaired_schema == json_schema:
                continue

            connection.execute(
                text(
                    "UPDATE output_schemas SET json_schema = CAST(:json_schema AS jsonb), "
                    "updated_at = NOW() WHERE id = :schema_id"
                ),
                {
                    "json_schema": json.dumps(
                        repaired_schema,
                        sort_keys=True,
                        separators=(",", ":"),
                    ),
                    "schema_id": schema_id,
                },
            )


def _sanitize_retired_stock_analysis_resources(engine: Engine, table_names: set[str]) -> None:
    targets = _load_retired_stock_analysis_sanitation_targets()

    with engine.begin() as connection:
        if "agents" in table_names:
            _delete_rows_by_column_values(
                connection,
                table_name="agents",
                column_name="key",
                values=targets.agent_keys,
            )
        if "workflows" in table_names:
            _delete_rows_by_column_values(
                connection,
                table_name="workflows",
                column_name="key",
                values=targets.workflow_keys,
            )
        if "capabilities" in table_names:
            _delete_rows_by_column_values(
                connection,
                table_name="capabilities",
                column_name="key",
                values=targets.capability_keys,
            )
        if "mcp_servers" in table_names:
            _delete_rows_by_column_values(
                connection,
                table_name="mcp_servers",
                column_name="key",
                values=targets.mcp_server_keys,
            )
        if "output_schemas" in table_names:
            _delete_rows_by_column_values(
                connection,
                table_name="output_schemas",
                column_name="key",
                values=targets.output_schema_keys,
            )
        if "reports" in table_names:
            _delete_rows_by_column_values(
                connection,
                table_name="reports",
                column_name="slug",
                values=targets.report_slugs,
            )
        if "text_templates" in table_names:
            _delete_rows_by_column_values(
                connection,
                table_name="text_templates",
                column_name="name",
                values=targets.template_names,
            )
        if "portfolios" in table_names:
            retired_portfolio_ids = _select_ids_by_column_values(
                connection,
                table_name="portfolios",
                match_column="slug",
                values=targets.portfolio_slugs,
            )
            if retired_portfolio_ids:
                for child_table_name in ("trading_operations", "positions", "balances"):
                    if child_table_name in table_names:
                        _delete_rows_by_column_values(
                            connection,
                            table_name=child_table_name,
                            column_name="portfolio_id",
                            values=retired_portfolio_ids,
                        )
                _delete_rows_by_column_values(
                    connection,
                    table_name="portfolios",
                    column_name="id",
                    values=retired_portfolio_ids,
                )


def _drop_tables(engine: Engine, table_names: set[str], tables: tuple[str, ...]) -> None:
    with engine.begin() as connection:
        for table_name in tables:
            if table_name not in table_names:
                continue
            connection.exec_driver_sql(f'DROP TABLE IF EXISTS "{table_name}" CASCADE')
            table_names.discard(table_name)


def upgrade_legacy_schema(engine: Engine) -> None:
    validate_supported_database_engine(engine)
    inspector = inspect(engine)
    table_names = set(inspector.get_table_names())

    _cutover_capability_storage(engine, table_names)
    _ensure_run_target_identity_support(engine, table_names)
    _ensure_agent_platform_tables(engine, table_names)
    _ensure_model_connection_key_support(engine, table_names)
    _ensure_model_connection_api_style_support(engine, table_names)
    _ensure_agent_manifest_columns(engine, table_names)
    _ensure_workflow_manifest_columns(engine, table_names)
    _remove_dead_agent_runtime_fields(engine, table_names)
    _ensure_agent_model_connection_support(engine, table_names)
    _backfill_agent_model_connections(
        engine,
        table_names,
    )
    _ensure_agent_model_connection_snapshot_support(engine, table_names)
    _reset_legacy_mcp_server_table(engine, table_names)
    _flatten_legacy_mcp_server_rows(engine, table_names)
    _repair_retired_capability_tool_grants(engine, table_names)
    _repair_tradingagents_transition_output_schemas(engine, table_names)
    _recover_stale_agent_platform_runs(engine, table_names)

    if "portfolios" in table_names:
        portfolio_columns = {column["name"] for column in inspector.get_columns("portfolios")}
        if "slug" not in portfolio_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql("ALTER TABLE portfolios ADD COLUMN slug VARCHAR(100)")
                legacy_portfolios = connection.exec_driver_sql(
                    "SELECT id, name FROM portfolios ORDER BY id"
                ).all()
                used_slugs: set[str] = set()
                for portfolio_id, name in legacy_portfolios:
                    connection.execute(
                        text("UPDATE portfolios SET slug = :slug WHERE id = :portfolio_id"),
                        {
                            "slug": build_unique_legacy_portfolio_slug(
                                normalize_legacy_portfolio_slug(name), used_slugs
                            ),
                            "portfolio_id": portfolio_id,
                        },
                    )
                connection.exec_driver_sql("ALTER TABLE portfolios ALTER COLUMN slug SET NOT NULL")
                connection.exec_driver_sql(
                    "ALTER TABLE portfolios ADD CONSTRAINT uq_portfolios_slug UNIQUE (slug)"
                )

    if "balances" in table_names:
        balance_columns = {column["name"] for column in inspector.get_columns("balances")}
        if "operation_type" not in balance_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql("ALTER TABLE balances ADD COLUMN operation_type VARCHAR")
                connection.exec_driver_sql(
                    "UPDATE balances SET operation_type = 'DEPOSIT' WHERE operation_type IS NULL"
                )
                connection.exec_driver_sql(
                    "ALTER TABLE balances ALTER COLUMN operation_type SET NOT NULL"
                )

    if "reports" in table_names:
        report_columns = {column["name"] for column in inspector.get_columns("reports")}
        if "slug" not in report_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql("ALTER TABLE reports ADD COLUMN slug VARCHAR(200)")
                connection.exec_driver_sql("UPDATE reports SET slug = name WHERE slug IS NULL")
                connection.exec_driver_sql("ALTER TABLE reports ALTER COLUMN slug SET NOT NULL")
                connection.exec_driver_sql(
                    "ALTER TABLE reports ADD CONSTRAINT uq_reports_slug UNIQUE (slug)"
                )
        if "source" not in report_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql(
                    "ALTER TABLE reports ADD COLUMN source VARCHAR(20) DEFAULT 'compiled' NOT NULL"
                )
        if "metadata" not in report_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql(
                    "ALTER TABLE reports ADD COLUMN metadata JSONB DEFAULT '{}' NOT NULL"
                )

    if "market_quotes" in table_names:
        market_quote_columns = {column["name"] for column in inspector.get_columns("market_quotes")}
        if "name" not in market_quote_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql("ALTER TABLE market_quotes ADD COLUMN name VARCHAR(255)")

    _sanitize_retired_stock_analysis_resources(engine, table_names)
    _drop_tables(engine, table_names, _LEGACY_BACKEND_TABLES)
    _drop_tables(engine, table_names, _OBSOLETE_TABLES)
