from __future__ import annotations

import re

from sqlalchemy import inspect, text
from sqlalchemy.engine import Engine

from app.db.validation import validate_supported_database_engine

_OBSOLETE_TABLES = (
    "stock_analysis_versions",
    "stock_analysis_responses",
    "stock_analysis_requests",
    "stock_analysis_runs",
    "stock_analysis_conversations",
    "portfolio_stock_analysis_settings",
    "prompt_templates",
    "user_snippets",
    "llm_configs",
)
_LEGACY_BACKEND_TABLES = (
    "runtime_trace_events",
    "runtime_approvals",
    "runtime_checkpoints",
    "runtime_run_artifacts",
    "runtime_runs",
    "persona_projection_events",
    "capability_registry_entries",
    "persona_profiles",
    "workflow_specs",
    "agent_specs",
    "orchestration_characters",
    "orchestration_roles",
)
_LEGACY_SLUG_INVALID_CHARS_RE = re.compile(r"[^a-z0-9_]+")
_LEGACY_SLUG_DUPLICATE_UNDERSCORES_RE = re.compile(r"_+")
_AGENT_PLATFORM_RESTART_FAILURE_MESSAGE = (
    "Run marked as failed during startup recovery because the previous process exited while "
    "it was still running."
)
_AGENT_PLATFORM_TABLE_STATEMENTS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "output_schemas",
        (
            """
            CREATE TABLE IF NOT EXISTS output_schemas (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                kind VARCHAR(20) NOT NULL DEFAULT 'standalone',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                json_schema JSONB NOT NULL,
                registry_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_output_schemas_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_output_schemas_kind CHECK (kind IN ('standalone', 'shared')),
                CONSTRAINT ck_output_schemas_version_positive CHECK (version > 0),
                CONSTRAINT uq_output_schemas_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_output_schemas_key ON output_schemas (key)",
            "CREATE INDEX IF NOT EXISTS ix_output_schemas_status ON output_schemas (status)",
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_output_schemas_published_key "
                "ON output_schemas (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_output_schemas_draft_key "
                "ON output_schemas (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "skills",
        (
            """
            CREATE TABLE IF NOT EXISTS skills (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                tool_definitions JSONB NOT NULL DEFAULT '[]'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_skills_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_skills_version_positive CHECK (version > 0),
                CONSTRAINT uq_skills_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_skills_key ON skills (key)",
            "CREATE INDEX IF NOT EXISTS ix_skills_status ON skills (status)",
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_skills_published_key "
                "ON skills (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_skills_draft_key "
                "ON skills (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "mcp_servers",
        (
            """
            CREATE TABLE IF NOT EXISTS mcp_servers (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                transport VARCHAR(20) NOT NULL,
                command TEXT,
                url TEXT,
                auth JSONB NOT NULL DEFAULT '{}'::jsonb,
                enabled BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_mcp_servers_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_mcp_servers_transport CHECK (
                    transport IN ('stdio', 'http-sse')
                ),
                CONSTRAINT ck_mcp_servers_target CHECK (
                    (transport = 'stdio' AND command IS NOT NULL AND url IS NULL) OR
                    (transport = 'http-sse' AND url IS NOT NULL AND command IS NULL)
                ),
                CONSTRAINT ck_mcp_servers_version_positive CHECK (version > 0),
                CONSTRAINT uq_mcp_servers_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_mcp_servers_key ON mcp_servers (key)",
            "CREATE INDEX IF NOT EXISTS ix_mcp_servers_status ON mcp_servers (status)",
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_mcp_servers_published_key "
                "ON mcp_servers (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_mcp_servers_draft_key "
                "ON mcp_servers (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "agents",
        (
            """
            CREATE TABLE IF NOT EXISTS agents (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                model VARCHAR(200) NOT NULL,
                system_prompt TEXT NOT NULL,
                input_schema JSONB NOT NULL,
                output_schema_id INTEGER NOT NULL,
                output_schema_version INTEGER NOT NULL,
                skills JSONB NOT NULL DEFAULT '[]'::jsonb,
                mcp_servers JSONB NOT NULL DEFAULT '[]'::jsonb,
                temperature DOUBLE PRECISION NOT NULL DEFAULT 0,
                max_tool_rounds INTEGER NOT NULL DEFAULT 1,
                budget_usd NUMERIC(20, 8) NOT NULL DEFAULT 0,
                streaming BOOLEAN NOT NULL DEFAULT FALSE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_agents_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_agents_version_positive CHECK (version > 0),
                CONSTRAINT ck_agents_output_schema_version_positive CHECK (
                    output_schema_version > 0
                ),
                CONSTRAINT ck_agents_max_tool_rounds_positive CHECK (max_tool_rounds > 0),
                CONSTRAINT ck_agents_budget_usd_non_negative CHECK (budget_usd >= 0),
                CONSTRAINT uq_agents_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_agents_key ON agents (key)",
            "CREATE INDEX IF NOT EXISTS ix_agents_status ON agents (status)",
            (
                "CREATE INDEX IF NOT EXISTS ix_agents_output_schema "
                "ON agents (output_schema_id, output_schema_version)"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_agents_published_key "
                "ON agents (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_agents_draft_key "
                "ON agents (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "workflows",
        (
            """
            CREATE TABLE IF NOT EXISTS workflows (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                input_schema JSONB NOT NULL,
                steps JSONB NOT NULL,
                output_spec JSONB NOT NULL,
                aggregate_budget_usd NUMERIC(20, 8) NOT NULL DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_workflows_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_workflows_version_positive CHECK (version > 0),
                CONSTRAINT ck_workflows_aggregate_budget_non_negative CHECK (
                    aggregate_budget_usd >= 0
                ),
                CONSTRAINT uq_workflows_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_workflows_key ON workflows (key)",
            "CREATE INDEX IF NOT EXISTS ix_workflows_status ON workflows (status)",
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_workflows_published_key "
                "ON workflows (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_workflows_draft_key "
                "ON workflows (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "runs",
        (
            """
            CREATE TABLE IF NOT EXISTS runs (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                workflow_id INTEGER NOT NULL,
                workflow_key VARCHAR(120) NOT NULL,
                workflow_version INTEGER NOT NULL,
                input JSONB NOT NULL,
                per_step_outputs JSONB NOT NULL DEFAULT '{}'::jsonb,
                final_output JSONB,
                status VARCHAR(20) NOT NULL DEFAULT 'running',
                total_tokens INTEGER NOT NULL DEFAULT 0,
                total_cost_usd NUMERIC(20, 8) NOT NULL DEFAULT 0,
                trace_id VARCHAR(255),
                error TEXT,
                started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                finished_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_runs_status CHECK (status IN ('running', 'succeeded', 'failed')),
                CONSTRAINT ck_runs_workflow_version_positive CHECK (workflow_version > 0),
                CONSTRAINT ck_runs_total_tokens_non_negative CHECK (total_tokens >= 0),
                CONSTRAINT ck_runs_total_cost_non_negative CHECK (total_cost_usd >= 0)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_runs_status ON runs (status)",
            (
                "CREATE INDEX IF NOT EXISTS ix_runs_workflow "
                "ON runs (workflow_id, workflow_version)"
            ),
            (
                "CREATE INDEX IF NOT EXISTS ix_runs_workflow_key "
                "ON runs (workflow_key, workflow_version)"
            ),
        ),
    ),
)


def normalize_legacy_portfolio_slug(name: str) -> str:
    normalized = _LEGACY_SLUG_INVALID_CHARS_RE.sub("_", name.strip().lower())
    normalized = _LEGACY_SLUG_DUPLICATE_UNDERSCORES_RE.sub("_", normalized).strip("_")
    if not normalized:
        normalized = "portfolio"
    if not normalized[0].isalpha():
        normalized = f"portfolio_{normalized}"
    return normalized


def build_unique_legacy_portfolio_slug(base_slug: str, used_slugs: set[str]) -> str:
    suffix = ""
    sequence = 2

    while True:
        max_base_length = 100 - len(suffix)
        trimmed_base = base_slug[:max_base_length].rstrip("_")
        if not trimmed_base:
            trimmed_base = "portfolio"[:max_base_length].rstrip("_") or "p"

        candidate = f"{trimmed_base}{suffix}"
        if candidate not in used_slugs:
            used_slugs.add(candidate)
            return candidate

        suffix = f"_{sequence}"
        sequence += 1


def _ensure_agent_platform_tables(engine: Engine, table_names: set[str]) -> None:
    with engine.begin() as connection:
        for table_name, statements in _AGENT_PLATFORM_TABLE_STATEMENTS:
            for statement in statements:
                connection.exec_driver_sql(statement)
            table_names.add(table_name)


def _recover_stale_agent_platform_runs(engine: Engine, table_names: set[str]) -> None:
    if "runs" not in table_names:
        return

    with engine.begin() as connection:
        connection.execute(
            text(
                """
                UPDATE runs
                SET status = 'failed',
                    error = COALESCE(NULLIF(error, ''), :restart_failure_message),
                    finished_at = COALESCE(finished_at, NOW()),
                    updated_at = NOW()
                WHERE status = 'running'
                """
            ),
            {"restart_failure_message": _AGENT_PLATFORM_RESTART_FAILURE_MESSAGE},
        )


def _drop_tables(engine: Engine, table_names: set[str], tables: tuple[str, ...]) -> None:
    with engine.begin() as connection:
        for table_name in tables:
            if table_name not in table_names:
                continue
            connection.exec_driver_sql(f'DROP TABLE IF EXISTS "{table_name}" CASCADE')
            table_names.discard(table_name)


def upgrade_legacy_schema(engine: Engine) -> None:
    validate_supported_database_engine(engine)
    inspector = inspect(engine)
    table_names = set(inspector.get_table_names())

    _ensure_agent_platform_tables(engine, table_names)
    _recover_stale_agent_platform_runs(engine, table_names)

    if "portfolios" in table_names:
        portfolio_columns = {column["name"] for column in inspector.get_columns("portfolios")}
        if "slug" not in portfolio_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql("ALTER TABLE portfolios ADD COLUMN slug VARCHAR(100)")
                legacy_portfolios = connection.exec_driver_sql(
                    "SELECT id, name FROM portfolios ORDER BY id"
                ).all()
                used_slugs: set[str] = set()
                for portfolio_id, name in legacy_portfolios:
                    connection.execute(
                        text("UPDATE portfolios SET slug = :slug WHERE id = :portfolio_id"),
                        {
                            "slug": build_unique_legacy_portfolio_slug(
                                normalize_legacy_portfolio_slug(name), used_slugs
                            ),
                            "portfolio_id": portfolio_id,
                        },
                    )
                connection.exec_driver_sql("ALTER TABLE portfolios ALTER COLUMN slug SET NOT NULL")
                connection.exec_driver_sql(
                    "ALTER TABLE portfolios ADD CONSTRAINT uq_portfolios_slug UNIQUE (slug)"
                )

    if "balances" in table_names:
        balance_columns = {column["name"] for column in inspector.get_columns("balances")}
        if "operation_type" not in balance_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql("ALTER TABLE balances ADD COLUMN operation_type VARCHAR")
                connection.exec_driver_sql(
                    "UPDATE balances SET operation_type = 'DEPOSIT' WHERE operation_type IS NULL"
                )
                connection.exec_driver_sql(
                    "ALTER TABLE balances ALTER COLUMN operation_type SET NOT NULL"
                )

    if "reports" in table_names:
        report_columns = {column["name"] for column in inspector.get_columns("reports")}
        if "slug" not in report_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql("ALTER TABLE reports ADD COLUMN slug VARCHAR(200)")
                connection.exec_driver_sql("UPDATE reports SET slug = name WHERE slug IS NULL")
                connection.exec_driver_sql("ALTER TABLE reports ALTER COLUMN slug SET NOT NULL")
                connection.exec_driver_sql(
                    "ALTER TABLE reports ADD CONSTRAINT uq_reports_slug UNIQUE (slug)"
                )
        if "source" not in report_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql(
                    "ALTER TABLE reports ADD COLUMN source VARCHAR(20) DEFAULT 'compiled' NOT NULL"
                )
        if "metadata" not in report_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql(
                    "ALTER TABLE reports ADD COLUMN metadata JSONB DEFAULT '{}' NOT NULL"
                )

    if "market_quotes" in table_names:
        market_quote_columns = {column["name"] for column in inspector.get_columns("market_quotes")}
        if "name" not in market_quote_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql("ALTER TABLE market_quotes ADD COLUMN name VARCHAR(255)")

    _drop_tables(engine, table_names, _LEGACY_BACKEND_TABLES)
    _drop_tables(engine, table_names, _OBSOLETE_TABLES)
