from __future__ import annotations

import json
import re

from sqlalchemy import bindparam, inspect, text
from sqlalchemy.engine import Engine

from app.agents.tool_catalog.server_declared import SERVER_DECLARED_TOOL_REGISTRY
from app.db.validation import validate_supported_database_engine
from app.models.agent import (
    AGENT_MANIFEST_API_VERSION,
    AGENT_MANIFEST_COMPILER_VERSION,
    TEMPORARY_AGENT_MANIFEST_HASH,
    TEMPORARY_AGENT_MANIFEST_SOURCE,
)
from app.models.mcp_server import flatten_mcp_server_storage_payload
from app.models.workflow import TEMPORARY_WORKFLOW_MANIFEST_SOURCE, WORKFLOW_MANIFEST_API_VERSION

_OBSOLETE_TABLES = (
    "stock_analysis_versions",
    "stock_analysis_responses",
    "stock_analysis_requests",
    "stock_analysis_runs",
    "stock_analysis_conversations",
    "portfolio_stock_analysis_settings",
    "prompt_templates",
    "user_snippets",
    "llm_configs",
)
_LEGACY_BACKEND_TABLES = (
    "runtime_trace_events",
    "runtime_approvals",
    "runtime_checkpoints",
    "runtime_run_artifacts",
    "runtime_runs",
    "persona_projection_events",
    "capability_registry_entries",
    "persona_profiles",
    "workflow_specs",
    "agent_specs",
    "orchestration_characters",
    "orchestration_roles",
)
_LEGACY_SLUG_INVALID_CHARS_RE = re.compile(r"[^a-z0-9_]+")
_LEGACY_SLUG_DUPLICATE_UNDERSCORES_RE = re.compile(r"_+")
_MODEL_CONNECTION_KEY_INVALID_CHARS_RE = re.compile(r"[^a-z0-9_]+")
_MODEL_CONNECTION_KEY_DUPLICATE_UNDERSCORES_RE = re.compile(r"_+")
_MODEL_CONNECTION_KEY_MAX_LENGTH = 120
_AGENT_PLATFORM_RESTART_FAILURE_MESSAGE = (
    "Run marked as failed during startup recovery because the previous process exited while "
    "it was still running."
)
_AGENT_PLATFORM_PENDING_SKIP_MESSAGE = (
    "Runtime row skipped during startup recovery because the parent run failed before it "
    "started."
)
_MODEL_CONNECTION_PLACEHOLDER_BASE_URL = "https://api.openai.com/v1"
_MODEL_CONNECTION_PLACEHOLDER_REASONING_EFFORT = "medium"
_MODEL_CONNECTION_PLACEHOLDER_TIMEOUT_SECONDS = 60
_MODEL_CONNECTION_REASONING_EFFORT_CHECK = "ck_model_connections_reasoning_effort"
_MODEL_CONNECTION_REASONING_EFFORT_CHECK_SQL = (
    "reasoning_effort IS NULL OR (length(btrim(reasoning_effort)) BETWEEN 1 AND 128)"
)
_MODEL_CONNECTION_DEFAULT_API_STYLE = "responses"
_MODEL_CONNECTION_ALLOWED_API_STYLES = ("responses", "chat_completions")


def _sql_string_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


_WORKFLOW_MANIFEST_API_VERSION_SQL = _sql_string_literal(WORKFLOW_MANIFEST_API_VERSION)
_TEMPORARY_WORKFLOW_MANIFEST_SOURCE_SQL = _sql_string_literal(TEMPORARY_WORKFLOW_MANIFEST_SOURCE)
_AGENT_MANIFEST_API_VERSION_SQL = _sql_string_literal(AGENT_MANIFEST_API_VERSION)
_TEMPORARY_AGENT_MANIFEST_SOURCE_SQL = _sql_string_literal(TEMPORARY_AGENT_MANIFEST_SOURCE)
_TEMPORARY_AGENT_MANIFEST_HASH_SQL = _sql_string_literal(TEMPORARY_AGENT_MANIFEST_HASH)
_AGENT_MANIFEST_COMPILER_VERSION_SQL = _sql_string_literal(AGENT_MANIFEST_COMPILER_VERSION)
_AGENT_PLATFORM_TABLE_STATEMENTS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "output_schemas",
        (
            """
            CREATE TABLE IF NOT EXISTS output_schemas (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                kind VARCHAR(20) NOT NULL DEFAULT 'standalone',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                json_schema JSONB NOT NULL,
                registry_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_output_schemas_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_output_schemas_kind CHECK (kind IN ('standalone', 'shared')),
                CONSTRAINT ck_output_schemas_version_positive CHECK (version > 0),
                CONSTRAINT uq_output_schemas_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_output_schemas_key ON output_schemas (key)",
            "CREATE INDEX IF NOT EXISTS ix_output_schemas_status ON output_schemas (status)",
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_output_schemas_published_key "
                "ON output_schemas (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_output_schemas_draft_key "
                "ON output_schemas (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "capabilities",
        (
            """
            CREATE TABLE IF NOT EXISTS capabilities (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                tool_keys JSONB NOT NULL DEFAULT '[]'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_capabilities_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_capabilities_version_positive CHECK (version > 0),
                CONSTRAINT uq_capabilities_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_capabilities_key ON capabilities (key)",
            "CREATE INDEX IF NOT EXISTS ix_capabilities_status ON capabilities (status)",
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_capabilities_published_key "
                "ON capabilities (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_capabilities_draft_key "
                "ON capabilities (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "mcp_servers",
        (
            """
            CREATE TABLE IF NOT EXISTS mcp_servers (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                config JSONB NOT NULL DEFAULT '{}'::jsonb,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_mcp_servers_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_mcp_servers_version_positive CHECK (version > 0),
                CONSTRAINT uq_mcp_servers_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_mcp_servers_key ON mcp_servers (key)",
            "CREATE INDEX IF NOT EXISTS ix_mcp_servers_status ON mcp_servers (status)",
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_mcp_servers_published_key "
                "ON mcp_servers (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_mcp_servers_draft_key "
                "ON mcp_servers (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "model_connections",
        (
            """
            CREATE TABLE IF NOT EXISTS model_connections (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'active',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                base_url VARCHAR(500) NOT NULL,
                organization VARCHAR(200),
                project VARCHAR(200),
                model_id VARCHAR(200) NOT NULL,
                reasoning_effort VARCHAR(128) DEFAULT 'medium',
                api_style VARCHAR(30) NOT NULL DEFAULT 'responses',
                timeout_seconds INTEGER NOT NULL DEFAULT 60,
                secret_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
                has_api_key BOOLEAN NOT NULL DEFAULT FALSE,
                api_key_last4 VARCHAR(4),
                last_tested_at TIMESTAMPTZ,
                last_test_ok BOOLEAN,
                last_test_message TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_model_connections_status CHECK (
                    status IN ('active', 'archived')
                ),
                CONSTRAINT ck_model_connections_reasoning_effort CHECK (
                    reasoning_effort IS NULL
                    OR (length(btrim(reasoning_effort)) BETWEEN 1 AND 128)
                ),
                CONSTRAINT ck_model_connections_api_style CHECK (
                    api_style IN ('responses', 'chat_completions')
                ),
                CONSTRAINT ck_model_connections_timeout_seconds_positive CHECK (
                    timeout_seconds > 0
                ),
                CONSTRAINT uq_model_connections_key UNIQUE (key)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_model_connections_status ON model_connections (status)",
            (
                "CREATE INDEX IF NOT EXISTS ix_model_connections_model_id "
                "ON model_connections (model_id)"
            ),
        ),
    ),
    (
        "agents",
        (
            """
            CREATE TABLE IF NOT EXISTS agents (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                manifest_api_version VARCHAR(80) NOT NULL DEFAULT 'ledger.agent/v1',
                manifest_source TEXT NOT NULL DEFAULT $$apiVersion: ledger.agent/v1
kind: Agent
metadata:
  source: legacy-payload-placeholder
$$,
                manifest_hash VARCHAR(64) NOT NULL DEFAULT
                    '98e17b8a6f1bd584aab673e2ab817f26173a7a1cd19ec5890c5bd2f0099c2f3b',
                compiler_version VARCHAR(80) NOT NULL DEFAULT 'agent-manifest-compiler/v1',
                model_connection_id INTEGER,
                model_connection_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
                model VARCHAR(200) NOT NULL,
                system_prompt TEXT NOT NULL,
                input_schema JSONB NOT NULL,
                output_schema_id INTEGER NOT NULL,
                output_schema_version INTEGER NOT NULL,
                capabilities JSONB NOT NULL DEFAULT '[]'::jsonb,
                mcp_servers JSONB NOT NULL DEFAULT '[]'::jsonb,
                budget_usd NUMERIC(20, 8) NOT NULL DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_agents_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_agents_version_positive CHECK (version > 0),
                CONSTRAINT ck_agents_output_schema_version_positive CHECK (
                    output_schema_version > 0
                ),
                CONSTRAINT ck_agents_budget_usd_non_negative CHECK (budget_usd >= 0),
                CONSTRAINT uq_agents_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_agents_key ON agents (key)",
            "CREATE INDEX IF NOT EXISTS ix_agents_status ON agents (status)",
            (
                "CREATE INDEX IF NOT EXISTS ix_agents_output_schema "
                "ON agents (output_schema_id, output_schema_version)"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_agents_published_key "
                "ON agents (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_agents_draft_key "
                "ON agents (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "workflows",
        (
            """
            CREATE TABLE IF NOT EXISTS workflows (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                key VARCHAR(120) NOT NULL,
                version INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'draft',
                name VARCHAR(200) NOT NULL,
                description TEXT NOT NULL DEFAULT '',
                manifest_api_version VARCHAR(80) NOT NULL DEFAULT 'ledger.workflow/v1',
                manifest_source TEXT NOT NULL DEFAULT $$apiVersion: ledger.workflow/v1
kind: Workflow
metadata:
  source: legacy-payload-placeholder
$$,
                input_schema JSONB NOT NULL,
                steps JSONB NOT NULL,
                output_spec JSONB NOT NULL,
                aggregate_budget_usd NUMERIC(20, 8) NOT NULL DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_workflows_status CHECK (
                    status IN ('draft', 'published', 'deprecated', 'archived')
                ),
                CONSTRAINT ck_workflows_version_positive CHECK (version > 0),
                CONSTRAINT ck_workflows_aggregate_budget_non_negative CHECK (
                    aggregate_budget_usd >= 0
                ),
                CONSTRAINT uq_workflows_key_version UNIQUE (key, version)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_workflows_key ON workflows (key)",
            "CREATE INDEX IF NOT EXISTS ix_workflows_status ON workflows (status)",
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_workflows_published_key "
                "ON workflows (key) WHERE status = 'published'"
            ),
            (
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_workflows_draft_key "
                "ON workflows (key) WHERE status = 'draft'"
            ),
        ),
    ),
    (
        "runs",
        (
            """
            CREATE TABLE IF NOT EXISTS runs (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                target_kind VARCHAR(20) NOT NULL,
                target_id INTEGER NOT NULL,
                target_key VARCHAR(120) NOT NULL,
                target_version INTEGER NOT NULL,
                input JSONB NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'queued',
                source_run_id INTEGER REFERENCES runs(id) ON DELETE SET NULL,
                lineage_root_run_id INTEGER REFERENCES runs(id) ON DELETE SET NULL,
                forked_from_step_index INTEGER,
                resume_step_index INTEGER NOT NULL DEFAULT 1,
                final_output JSONB,
                total_tokens INTEGER NOT NULL DEFAULT 0,
                inherited_tokens INTEGER NOT NULL DEFAULT 0,
                executed_tokens INTEGER NOT NULL DEFAULT 0,
                trace_id VARCHAR(255),
                error TEXT,
                queued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                started_at TIMESTAMPTZ,
                finished_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT ck_runs_target_kind CHECK (target_kind IN ('agent', 'workflow')),
                CONSTRAINT ck_runs_status CHECK (
                    status IN ('queued', 'running', 'succeeded', 'failed')
                ),
                CONSTRAINT ck_runs_target_version_positive CHECK (target_version > 0),
                CONSTRAINT ck_runs_resume_step_index_positive CHECK (resume_step_index > 0),
                CONSTRAINT ck_runs_forked_from_step_index_positive CHECK (
                    forked_from_step_index IS NULL OR forked_from_step_index > 0
                ),
                CONSTRAINT ck_runs_total_tokens_non_negative CHECK (total_tokens >= 0),
                CONSTRAINT ck_runs_inherited_tokens_non_negative CHECK (inherited_tokens >= 0),
                CONSTRAINT ck_runs_executed_tokens_non_negative CHECK (executed_tokens >= 0)
            )
            """,
            "CREATE INDEX IF NOT EXISTS ix_runs_status ON runs (status)",
            (
                "CREATE INDEX IF NOT EXISTS ix_runs_target "
                "ON runs (target_kind, target_id, target_version)"
            ),
            (
                "CREATE INDEX IF NOT EXISTS ix_runs_target_key "
                "ON runs (target_kind, target_key, target_version)"
            ),
            "CREATE INDEX IF NOT EXISTS ix_runs_source_run ON runs (source_run_id)",
            "CREATE INDEX IF NOT EXISTS ix_runs_lineage_root ON runs (lineage_root_run_id)",
        ),
    ),
    (
        "run_steps",
        (
            """
            CREATE TABLE IF NOT EXISTS run_steps (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
                step_index INTEGER NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'pending',
                origin VARCHAR(20) NOT NULL DEFAULT 'planned',
                source_run_step_id INTEGER REFERENCES run_steps(id) ON DELETE SET NULL,
                source_run_id INTEGER REFERENCES runs(id) ON DELETE SET NULL,
                source_step_index INTEGER,
                graph_metadata JSONB,
                error TEXT,
                started_at TIMESTAMPTZ,
                finished_at TIMESTAMPTZ,
                persisted_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT uq_run_steps_run_step_index UNIQUE (run_id, step_index),
                CONSTRAINT ck_run_steps_step_index_positive CHECK (step_index > 0),
                CONSTRAINT ck_run_steps_status CHECK (
                    status IN ('pending', 'running', 'succeeded', 'failed', 'skipped')
                ),
                CONSTRAINT ck_run_steps_origin CHECK (origin IN ('planned', 'copied')),
                CONSTRAINT ck_run_steps_source_step_index_positive CHECK (
                    source_step_index IS NULL OR source_step_index > 0
                )
            )
            """,
            (
                "CREATE INDEX IF NOT EXISTS ix_run_steps_run_step_index "
                "ON run_steps (run_id, step_index)"
            ),
            ("CREATE INDEX IF NOT EXISTS ix_run_steps_run_status " "ON run_steps (run_id, status)"),
            (
                "CREATE INDEX IF NOT EXISTS ix_run_steps_source_run_step "
                "ON run_steps (source_run_step_id)"
            ),
        ),
    ),
    (
        "run_agent_invocations",
        (
            """
            CREATE TABLE IF NOT EXISTS run_agent_invocations (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                run_step_id INTEGER NOT NULL REFERENCES run_steps(id) ON DELETE CASCADE,
                run_id INTEGER NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
                step_index INTEGER NOT NULL,
                slot VARCHAR(120) NOT NULL,
                position INTEGER NOT NULL DEFAULT 0,
                agent_id INTEGER NOT NULL,
                agent_key VARCHAR(120) NOT NULL,
                agent_version INTEGER NOT NULL,
                output_schema_id INTEGER NOT NULL,
                output_schema_version INTEGER NOT NULL,
                input_mode VARCHAR(20) NOT NULL DEFAULT 'wired',
                wiring JSONB NOT NULL DEFAULT '{}'::jsonb,
                graph_metadata JSONB,
                optional BOOLEAN NOT NULL DEFAULT FALSE,
                status VARCHAR(20) NOT NULL DEFAULT 'pending',
                resolved_input JSONB NOT NULL DEFAULT '{}'::jsonb,
                resolved_input_origin VARCHAR(20) NOT NULL DEFAULT 'derived',
                output JSONB,
                output_origin VARCHAR(20),
                error_code VARCHAR(120),
                error_message TEXT,
                error_details JSONB NOT NULL DEFAULT '[]'::jsonb,
                tokens INTEGER NOT NULL DEFAULT 0,
                duration_ms INTEGER,
                trace_span_id VARCHAR(255),
                source_invocation_id INTEGER REFERENCES run_agent_invocations(id)
                    ON DELETE SET NULL,
                started_at TIMESTAMPTZ,
                finished_at TIMESTAMPTZ,
                persisted_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                CONSTRAINT uq_run_agent_invocations_step_slot UNIQUE (run_step_id, slot),
                CONSTRAINT ck_run_agent_invocations_step_index_positive CHECK (step_index > 0),
                CONSTRAINT ck_run_agent_invocations_position_non_negative CHECK (position >= 0),
                CONSTRAINT ck_run_agent_invocations_agent_id_positive CHECK (agent_id > 0),
                CONSTRAINT ck_run_agent_invocations_agent_version_positive CHECK (
                    agent_version > 0
                ),
                CONSTRAINT ck_run_agent_invocations_output_schema_id_positive CHECK (
                    output_schema_id > 0
                ),
                CONSTRAINT ck_run_agent_invocations_output_schema_version_positive CHECK (
                    output_schema_version > 0
                ),
                CONSTRAINT ck_run_agent_invocations_input_mode CHECK (
                    input_mode IN ('passthrough', 'wired')
                ),
                CONSTRAINT ck_run_agent_invocations_status CHECK (
                    status IN ('pending', 'running', 'succeeded', 'failed', 'skipped')
                ),
                CONSTRAINT ck_run_agent_invocations_resolved_input_origin CHECK (
                    resolved_input_origin IN ('derived', 'edited', 'copied', 'passthrough')
                ),
                CONSTRAINT ck_run_agent_invocations_output_origin CHECK (
                    output_origin IS NULL OR output_origin IN ('executed', 'edited', 'copied')
                ),
                CONSTRAINT ck_run_agent_invocations_tokens_non_negative CHECK (tokens >= 0),
                CONSTRAINT ck_run_agent_invocations_duration_non_negative CHECK (
                    duration_ms IS NULL OR duration_ms >= 0
                )
            )
            """,
            (
                "CREATE INDEX IF NOT EXISTS ix_run_agent_invocations_run_step_index "
                "ON run_agent_invocations (run_id, step_index)"
            ),
            (
                "CREATE INDEX IF NOT EXISTS ix_run_agent_invocations_run_status "
                "ON run_agent_invocations (run_id, status)"
            ),
            (
                "CREATE INDEX IF NOT EXISTS ix_run_agent_invocations_agent_version "
                "ON run_agent_invocations (agent_key, agent_version)"
            ),
            (
                "CREATE INDEX IF NOT EXISTS ix_run_agent_invocations_source_invocation "
                "ON run_agent_invocations (source_invocation_id)"
            ),
        ),
    ),
)

_RUNTIME_HARD_CUTOVER_DROP_ORDER = (
    "run_agent_invocations",
    "run_steps",
    "runs",
    "agents",
    "workflows",
    "output_schemas",
)
_RUNTIME_HARD_CUTOVER_CREATE_ORDER = (
    "output_schemas",
    "agents",
    "workflows",
    "runs",
    "run_steps",
    "run_agent_invocations",
)
_RUNTIME_REQUIRED_COLUMNS: dict[str, frozenset[str]] = {
    "output_schemas": frozenset(
        {
            "id",
            "key",
            "version",
            "status",
            "kind",
            "name",
            "description",
            "json_schema",
            "registry_refs",
            "created_at",
            "updated_at",
        }
    ),
    "agents": frozenset(
        {
            "id",
            "key",
            "version",
            "status",
            "name",
            "description",
            "manifest_api_version",
            "manifest_source",
            "manifest_hash",
            "compiler_version",
            "model_connection_id",
            "model_connection_snapshot",
            "model",
            "system_prompt",
            "input_schema",
            "output_schema_id",
            "output_schema_version",
            "capabilities",
            "mcp_servers",
            "budget_usd",
            "created_at",
            "updated_at",
        }
    ),
    "workflows": frozenset(
        {
            "id",
            "key",
            "version",
            "status",
            "name",
            "description",
            "manifest_api_version",
            "manifest_source",
            "input_schema",
            "steps",
            "output_spec",
            "aggregate_budget_usd",
            "created_at",
            "updated_at",
        }
    ),
    "runs": frozenset(
        {
            "id",
            "target_kind",
            "target_id",
            "target_key",
            "target_version",
            "input",
            "status",
            "source_run_id",
            "lineage_root_run_id",
            "forked_from_step_index",
            "resume_step_index",
            "final_output",
            "total_tokens",
            "inherited_tokens",
            "executed_tokens",
            "trace_id",
            "error",
            "queued_at",
            "started_at",
            "finished_at",
            "created_at",
            "updated_at",
        }
    ),
    "run_steps": frozenset(
        {
            "id",
            "run_id",
            "step_index",
            "status",
            "origin",
            "source_run_step_id",
            "source_run_id",
            "source_step_index",
            "error",
            "started_at",
            "finished_at",
            "persisted_at",
            "created_at",
            "updated_at",
        }
    ),
    "run_agent_invocations": frozenset(
        {
            "id",
            "run_step_id",
            "run_id",
            "step_index",
            "slot",
            "position",
            "agent_id",
            "agent_key",
            "agent_version",
            "output_schema_id",
            "output_schema_version",
            "input_mode",
            "wiring",
            "optional",
            "status",
            "resolved_input",
            "resolved_input_origin",
            "output",
            "output_origin",
            "error_code",
            "error_message",
            "error_details",
            "tokens",
            "duration_ms",
            "trace_span_id",
            "source_invocation_id",
            "started_at",
            "finished_at",
            "persisted_at",
            "created_at",
            "updated_at",
        }
    ),
}
_RUNTIME_CUTOVER_REQUIRED_COLUMNS: dict[str, frozenset[str]] = {
    table_name: (
        _RUNTIME_REQUIRED_COLUMNS[table_name] - {"queued_at"}
        if table_name == "runs"
        else _RUNTIME_REQUIRED_COLUMNS[table_name]
    )
    for table_name in ("runs", "run_steps", "run_agent_invocations")
}
_RUNTIME_LEGACY_COLUMNS: dict[str, frozenset[str]] = {
    "runs": frozenset({"workflow_id", "workflow_key", "workflow_version", "per_step_outputs"}),
}


def normalize_legacy_portfolio_slug(name: str) -> str:
    normalized = _LEGACY_SLUG_INVALID_CHARS_RE.sub("_", name.strip().lower())
    normalized = _LEGACY_SLUG_DUPLICATE_UNDERSCORES_RE.sub("_", normalized).strip("_")
    if not normalized:
        normalized = "portfolio"
    if not normalized[0].isalpha():
        normalized = f"portfolio_{normalized}"
    return normalized


def build_unique_legacy_portfolio_slug(base_slug: str, used_slugs: set[str]) -> str:
    suffix = ""
    sequence = 2

    while True:
        max_base_length = 100 - len(suffix)
        trimmed_base = base_slug[:max_base_length].rstrip("_")
        if not trimmed_base:
            trimmed_base = "portfolio"[:max_base_length].rstrip("_") or "p"

        candidate = f"{trimmed_base}{suffix}"
        if candidate not in used_slugs:
            used_slugs.add(candidate)
            return candidate

        suffix = f"_{sequence}"
        sequence += 1


def normalize_legacy_model_connection_key(
    *,
    name: str | None,
    model_id: str | None,
) -> str:
    for raw_value in (name, model_id, "model_connection"):
        if raw_value is None:
            continue
        normalized = _MODEL_CONNECTION_KEY_INVALID_CHARS_RE.sub(
            "_",
            str(raw_value).strip().lower(),
        )
        normalized = _MODEL_CONNECTION_KEY_DUPLICATE_UNDERSCORES_RE.sub(
            "_",
            normalized,
        ).strip("_")
        if normalized:
            break
    else:
        normalized = "model_connection"

    if not normalized[0].isalpha():
        normalized = f"model_connection_{normalized}"
    return normalized[:_MODEL_CONNECTION_KEY_MAX_LENGTH].rstrip("_") or "model_connection"


def build_unique_model_connection_key(base_key: str, used_keys: set[str]) -> str:
    suffix = ""
    sequence = 2

    while True:
        max_base_length = _MODEL_CONNECTION_KEY_MAX_LENGTH - len(suffix)
        trimmed_base = base_key[:max_base_length].rstrip("_")
        if not trimmed_base:
            trimmed_base = "model_connection"[:max_base_length].rstrip("_") or "m"

        candidate = f"{trimmed_base}{suffix}"
        if candidate not in used_keys:
            used_keys.add(candidate)
            return candidate

        suffix = f"_{sequence}"
        sequence += 1


def _refresh_table_names(engine: Engine, table_names: set[str]) -> None:
    table_names.clear()
    table_names.update(inspect(engine).get_table_names())


def _cutover_capability_storage(engine: Engine, table_names: set[str]) -> None:
    legacy_storage_detected = _legacy_capability_storage_detected(engine, table_names)
    _drop_legacy_capability_tables(engine, table_names)
    _ensure_capability_tool_keys_column(engine, table_names)
    _ensure_agent_capabilities_column(engine, table_names)

    if legacy_storage_detected:
        _delete_all_capabilities_and_clear_agent_refs(engine, table_names)
    else:
        _delete_capabilities_with_stale_tool_keys(engine, table_names)
    _refresh_table_names(engine, table_names)


def _legacy_capability_storage_detected(engine: Engine, table_names: set[str]) -> bool:
    if {"skills", "capability_registry_entries"} & table_names:
        return True

    inspector = inspect(engine)
    if "capabilities" in table_names:
        capability_columns = {column["name"] for column in inspector.get_columns("capabilities")}
        if {"tool_grants", "tool_definitions"} & capability_columns:
            return True
    if "agents" in table_names:
        agent_columns = {column["name"] for column in inspector.get_columns("agents")}
        if "skills" in agent_columns:
            return True
    return False


def _drop_legacy_capability_tables(engine: Engine, table_names: set[str]) -> None:
    with engine.begin() as connection:
        for table_name in ("capability_registry_entries", "skills"):
            _ = connection.exec_driver_sql(f'DROP TABLE IF EXISTS "{table_name}" CASCADE')
            table_names.discard(table_name)


def _ensure_capability_tool_keys_column(engine: Engine, table_names: set[str]) -> None:
    if "capabilities" not in table_names:
        return

    capability_columns = {column["name"] for column in inspect(engine).get_columns("capabilities")}
    with engine.begin() as connection:
        if "tool_keys" not in capability_columns:
            _ = connection.exec_driver_sql(
                "ALTER TABLE capabilities ADD COLUMN tool_keys JSONB NOT NULL DEFAULT '[]'::jsonb"
            )
        _ = connection.exec_driver_sql(
            " ".join(
                (
                    "UPDATE capabilities SET tool_keys = '[]'::jsonb",
                    "WHERE tool_keys IS NULL OR jsonb_typeof(tool_keys) <> 'array'",
                )
            )
        )
        _ = connection.exec_driver_sql(
            "ALTER TABLE capabilities ALTER COLUMN tool_keys SET DEFAULT '[]'::jsonb"
        )
        _ = connection.exec_driver_sql(
            "ALTER TABLE capabilities ALTER COLUMN tool_keys SET NOT NULL"
        )
        _ = connection.exec_driver_sql("ALTER TABLE capabilities DROP COLUMN IF EXISTS tool_grants")
        _ = connection.exec_driver_sql(
            "ALTER TABLE capabilities DROP COLUMN IF EXISTS tool_definitions"
        )


def _ensure_agent_capabilities_column(engine: Engine, table_names: set[str]) -> None:
    if "agents" not in table_names:
        return

    agent_columns = {column["name"] for column in inspect(engine).get_columns("agents")}
    with engine.begin() as connection:
        if "capabilities" not in agent_columns:
            _ = connection.exec_driver_sql(
                "ALTER TABLE agents ADD COLUMN capabilities JSONB NOT NULL DEFAULT '[]'::jsonb"
            )
        _ = connection.exec_driver_sql(
            "UPDATE agents SET capabilities = '[]'::jsonb WHERE capabilities IS NULL"
        )
        _ = connection.exec_driver_sql(
            "ALTER TABLE agents ALTER COLUMN capabilities SET DEFAULT '[]'::jsonb"
        )
        _ = connection.exec_driver_sql("ALTER TABLE agents ALTER COLUMN capabilities SET NOT NULL")
        _ = connection.exec_driver_sql("ALTER TABLE agents DROP COLUMN IF EXISTS skills")


def _delete_all_capabilities_and_clear_agent_refs(engine: Engine, table_names: set[str]) -> None:
    with engine.begin() as connection:
        if "agents" in table_names:
            _ = connection.exec_driver_sql("UPDATE agents SET capabilities = '[]'::jsonb")
        if "capabilities" in table_names:
            _ = connection.exec_driver_sql("DELETE FROM capabilities")


def _delete_capabilities_with_stale_tool_keys(engine: Engine, table_names: set[str]) -> None:
    if "capabilities" not in table_names:
        return

    known_tool_keys = sorted(SERVER_DECLARED_TOOL_REGISTRY)
    with engine.begin() as connection:
        stale_count = int(
            connection.execute(
                text(
                    """
                    SELECT COUNT(*)
                    FROM capabilities AS capability
                    WHERE EXISTS (
                        SELECT 1
                        FROM jsonb_array_elements(capability.tool_keys) AS tool_key(value)
                        WHERE jsonb_typeof(tool_key.value) <> 'string'
                           OR tool_key.value #>> '{}' <> ALL(:known_tool_keys)
                    )
                    """
                ),
                {"known_tool_keys": known_tool_keys},
            ).scalar_one()
        )
        if not stale_count:
            return
        if "agents" in table_names:
            _ = connection.exec_driver_sql("UPDATE agents SET capabilities = '[]'::jsonb")
        _ = connection.execute(
            text(
                """
                DELETE FROM capabilities AS capability
                WHERE EXISTS (
                    SELECT 1
                    FROM jsonb_array_elements(capability.tool_keys) AS tool_key(value)
                    WHERE jsonb_typeof(tool_key.value) <> 'string'
                       OR tool_key.value #>> '{}' <> ALL(:known_tool_keys)
                )
                """
            ),
            {"known_tool_keys": known_tool_keys},
        )


def _ensure_agent_platform_tables(engine: Engine, table_names: set[str]) -> None:
    with engine.begin() as connection:
        for table_name, statements in _AGENT_PLATFORM_TABLE_STATEMENTS:
            for statement in statements:
                connection.exec_driver_sql(statement)
            table_names.add(table_name)


def _agent_platform_hard_cutover_required(engine: Engine, table_names: set[str]) -> bool:
    """Detect stale execution storage, not backfillable authoring-column drift."""
    inspector = inspect(engine)
    for table_name, required_columns in _RUNTIME_CUTOVER_REQUIRED_COLUMNS.items():
        if table_name not in table_names:
            continue
        columns = {column["name"] for column in inspector.get_columns(table_name)}
        if _RUNTIME_LEGACY_COLUMNS.get(table_name, frozenset()) & columns:
            return True
        if not required_columns <= columns:
            return True
    return False


def _reset_agent_platform_runtime_tables(engine: Engine, table_names: set[str]) -> None:
    statements_by_table = dict(_AGENT_PLATFORM_TABLE_STATEMENTS)
    with engine.begin() as connection:
        for table_name in _RUNTIME_HARD_CUTOVER_DROP_ORDER:
            connection.exec_driver_sql(f'DROP TABLE IF EXISTS "{table_name}" CASCADE')
            table_names.discard(table_name)
        for table_name in _RUNTIME_HARD_CUTOVER_CREATE_ORDER:
            for statement in statements_by_table[table_name]:
                connection.exec_driver_sql(statement)
            table_names.add(table_name)


def _ensure_model_connection_key_support(engine: Engine, table_names: set[str]) -> None:
    if "model_connections" not in table_names:
        return

    inspector = inspect(engine)
    model_connection_columns = {
        column["name"]: column for column in inspector.get_columns("model_connections")
    }
    model_connection_unique_constraints = {
        constraint["name"]
        for constraint in inspector.get_unique_constraints("model_connections")
        if constraint.get("name")
    }

    with engine.begin() as connection:
        if "key" not in model_connection_columns:
            connection.exec_driver_sql("ALTER TABLE model_connections ADD COLUMN key VARCHAR(120)")

        model_connection_rows = (
            connection.execute(
                text("SELECT id, key, name, model_id FROM model_connections ORDER BY id ASC")
            )
            .mappings()
            .all()
        )
        used_keys: set[str] = set()
        for row in model_connection_rows:
            raw_key = row["key"]
            raw_key_text = str(raw_key).strip() if raw_key is not None else ""
            base_key = normalize_legacy_model_connection_key(
                name=raw_key_text or row["name"],
                model_id=row["model_id"],
            )
            stable_key = build_unique_model_connection_key(base_key, used_keys)
            if raw_key_text != stable_key:
                connection.execute(
                    text(
                        "UPDATE model_connections "
                        "SET key = :key, updated_at = NOW() "
                        "WHERE id = :connection_id"
                    ),
                    {"key": stable_key, "connection_id": row["id"]},
                )

        connection.exec_driver_sql("ALTER TABLE model_connections ALTER COLUMN key SET NOT NULL")
        if "uq_model_connections_key" not in model_connection_unique_constraints:
            connection.exec_driver_sql(
                "ALTER TABLE model_connections ADD CONSTRAINT uq_model_connections_key UNIQUE (key)"
            )
        connection.exec_driver_sql(
            "CREATE INDEX IF NOT EXISTS ix_model_connections_key ON model_connections (key)"
        )


def _is_flexible_model_connection_reasoning_effort_check(sqltext: object) -> bool:
    normalized_sql = re.sub(r"\s+", " ", str(sqltext or "").lower())
    return all(
        token in normalized_sql
        for token in ("reasoning_effort", "is null", "length", "btrim", "128")
    )


def _ensure_model_connection_reasoning_effort_support(
    engine: Engine,
    table_names: set[str],
) -> None:
    if "model_connections" not in table_names:
        return

    inspector = inspect(engine)
    model_connection_columns = {
        column["name"]: column for column in inspector.get_columns("model_connections")
    }
    reasoning_effort_column = model_connection_columns.get("reasoning_effort")
    reasoning_effort_check = next(
        (
            constraint
            for constraint in inspector.get_check_constraints("model_connections")
            if constraint.get("name") == _MODEL_CONNECTION_REASONING_EFFORT_CHECK
        ),
        None,
    )
    has_flexible_reasoning_effort_check = (
        reasoning_effort_check is not None
        and _is_flexible_model_connection_reasoning_effort_check(
            reasoning_effort_check.get("sqltext")
        )
    )

    with engine.begin() as connection:
        if reasoning_effort_check is not None and not has_flexible_reasoning_effort_check:
            _ = connection.exec_driver_sql(
                "ALTER TABLE model_connections DROP CONSTRAINT "
                + _MODEL_CONNECTION_REASONING_EFFORT_CHECK
            )
            has_flexible_reasoning_effort_check = False

        if reasoning_effort_column is None:
            _ = connection.exec_driver_sql(
                " ".join(
                    (
                        "ALTER TABLE model_connections ADD COLUMN reasoning_effort",
                        "VARCHAR(128) DEFAULT 'medium'",
                    )
                )
            )
        else:
            _ = connection.exec_driver_sql(
                " ".join(
                    (
                        "ALTER TABLE model_connections ALTER COLUMN reasoning_effort",
                        "SET DEFAULT 'medium'",
                    )
                )
            )
            if reasoning_effort_column.get("nullable") is False:
                _ = connection.exec_driver_sql(
                    " ".join(
                        (
                            "ALTER TABLE model_connections ALTER COLUMN reasoning_effort",
                            "DROP NOT NULL",
                        )
                    )
                )
            if getattr(reasoning_effort_column.get("type"), "length", None) != 128:
                _ = connection.exec_driver_sql(
                    " ".join(
                        (
                            "ALTER TABLE model_connections ALTER COLUMN reasoning_effort",
                            "TYPE VARCHAR(128) USING reasoning_effort::VARCHAR(128)",
                        )
                    )
                )

        if not has_flexible_reasoning_effort_check:
            _ = connection.exec_driver_sql(
                " ".join(
                    (
                        "ALTER TABLE model_connections ADD CONSTRAINT",
                        _MODEL_CONNECTION_REASONING_EFFORT_CHECK,
                        f"CHECK ({_MODEL_CONNECTION_REASONING_EFFORT_CHECK_SQL})",
                    )
                )
            )


def _ensure_model_connection_api_style_support(engine: Engine, table_names: set[str]) -> None:
    if "model_connections" not in table_names:
        return

    inspector = inspect(engine)
    model_connection_columns = {
        column["name"]: column for column in inspector.get_columns("model_connections")
    }
    model_connection_check_constraints = {
        constraint["name"]
        for constraint in inspector.get_check_constraints("model_connections")
        if constraint.get("name")
    }

    with engine.begin() as connection:
        api_style_column = model_connection_columns.get("api_style")
        if api_style_column is None:
            _ = connection.exec_driver_sql(
                """
                ALTER TABLE model_connections
                ADD COLUMN api_style VARCHAR(30) NOT NULL DEFAULT 'responses'
                """
            )
        else:
            _ = connection.exec_driver_sql(
                "ALTER TABLE model_connections ALTER COLUMN api_style SET DEFAULT 'responses'"
            )

        _ = connection.execute(
            text(
                """
                UPDATE model_connections
                SET api_style = :default_api_style, updated_at = NOW()
                WHERE api_style IS NULL OR api_style NOT IN :allowed_api_styles
                """
            ).bindparams(bindparam("allowed_api_styles", expanding=True)),
            {
                "allowed_api_styles": _MODEL_CONNECTION_ALLOWED_API_STYLES,
                "default_api_style": _MODEL_CONNECTION_DEFAULT_API_STYLE,
            },
        )
        if api_style_column is None or api_style_column.get("nullable", True):
            _ = connection.exec_driver_sql(
                "ALTER TABLE model_connections ALTER COLUMN api_style SET NOT NULL"
            )
        if "ck_model_connections_api_style" not in model_connection_check_constraints:
            _ = connection.exec_driver_sql(
                """
                ALTER TABLE model_connections
                ADD CONSTRAINT ck_model_connections_api_style
                CHECK (api_style IN ('responses', 'chat_completions'))
                """
            )


def _ensure_agent_model_connection_support(engine: Engine, table_names: set[str]) -> None:
    if "agents" not in table_names:
        return

    inspector = inspect(engine)
    agent_columns = {column["name"] for column in inspector.get_columns("agents")}

    with engine.begin() as connection:
        if "model_connection_id" not in agent_columns:
            connection.exec_driver_sql("ALTER TABLE agents ADD COLUMN model_connection_id INTEGER")
        connection.exec_driver_sql(
            "CREATE INDEX IF NOT EXISTS ix_agents_model_connection ON agents (model_connection_id)"
        )


def _ensure_agent_model_connection_snapshot_support(engine: Engine, table_names: set[str]) -> None:
    if not {"agents", "model_connections"} <= table_names:
        return

    inspector = inspect(engine)
    agent_columns = {column["name"]: column for column in inspector.get_columns("agents")}
    model_connection_columns = {
        column["name"]: column for column in inspector.get_columns("model_connections")
    }
    api_style_snapshot_expression = (
        "CASE WHEN model_connection.api_style IN ('responses', 'chat_completions') "
        + "THEN model_connection.api_style ELSE 'responses' END"
        if "api_style" in model_connection_columns
        else "'responses'"
    )

    with engine.begin() as connection:
        if "model_connection_snapshot" not in agent_columns:
            connection.exec_driver_sql(
                "ALTER TABLE agents "
                "ADD COLUMN model_connection_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb"
            )

        _ = connection.execute(
            text(
                f"""
                UPDATE agents AS agent
                SET model_connection_snapshot = jsonb_build_object(
                        'base_url', model_connection.base_url,
                        'model_id', model_connection.model_id,
                        'organization', model_connection.organization,
                        'project', model_connection.project,
                        'reasoning_effort', model_connection.reasoning_effort,
                        'api_style', {api_style_snapshot_expression},
                        'timeout_seconds', model_connection.timeout_seconds
                    ),
                    updated_at = NOW()
                FROM model_connections AS model_connection
                WHERE agent.model_connection_id = model_connection.id
                  AND (
                    agent.model_connection_snapshot IS NULL
                    OR jsonb_typeof(agent.model_connection_snapshot) <> 'object'
                    OR agent.model_connection_snapshot = '{{}}'::jsonb
                    OR NOT (
                        agent.model_connection_snapshot ?& ARRAY[
                            'base_url',
                            'model_id',
                            'organization',
                            'project',
                            'reasoning_effort',
                            'api_style',
                            'timeout_seconds'
                        ]
                    )
                    OR COALESCE(agent.model_connection_snapshot->>'api_style', '') NOT IN (
                        'responses',
                        'chat_completions'
                    )
                    OR (
                        agent.model_connection_snapshot ? 'reasoning_effort'
                        AND agent.model_connection_snapshot->'reasoning_effort' <> 'null'::jsonb
                        AND (
                            jsonb_typeof(
                                agent.model_connection_snapshot->'reasoning_effort'
                            ) <> 'string'
                            OR length(
                                btrim(agent.model_connection_snapshot->>'reasoning_effort')
                            ) NOT BETWEEN 1 AND 128
                        )
                    )
                  )
                """
            )
        )
        connection.exec_driver_sql(
            "ALTER TABLE agents " "ALTER COLUMN model_connection_snapshot SET DEFAULT '{}'::jsonb"
        )
        snapshot_column = agent_columns.get("model_connection_snapshot")
        if snapshot_column is None or snapshot_column.get("nullable", True):
            connection.exec_driver_sql(
                "ALTER TABLE agents ALTER COLUMN model_connection_snapshot SET NOT NULL"
            )


def _ensure_agent_manifest_columns(engine: Engine, table_names: set[str]) -> None:
    if "agents" not in table_names:
        return

    inspector = inspect(engine)
    agent_columns = {column["name"]: column for column in inspector.get_columns("agents")}

    with engine.begin() as connection:
        if "manifest_api_version" not in agent_columns:
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ADD COLUMN manifest_api_version VARCHAR(80)
                NOT NULL DEFAULT {_AGENT_MANIFEST_API_VERSION_SQL}
                """
            )
        else:
            _ = connection.execute(
                text(
                    """
                    UPDATE agents
                    SET manifest_api_version = :manifest_api_version
                    WHERE manifest_api_version IS NULL
                    """
                ),
                {"manifest_api_version": AGENT_MANIFEST_API_VERSION},
            )
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ALTER COLUMN manifest_api_version
                SET DEFAULT {_AGENT_MANIFEST_API_VERSION_SQL}
                """
            )
            if agent_columns["manifest_api_version"].get("nullable", True):
                _ = connection.exec_driver_sql(
                    "ALTER TABLE agents ALTER COLUMN manifest_api_version SET NOT NULL"
                )

        if "manifest_source" not in agent_columns:
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ADD COLUMN manifest_source TEXT
                NOT NULL DEFAULT {_TEMPORARY_AGENT_MANIFEST_SOURCE_SQL}
                """
            )
        else:
            _ = connection.execute(
                text(
                    """
                    UPDATE agents
                    SET manifest_source = :manifest_source
                    WHERE manifest_source IS NULL
                    """
                ),
                {"manifest_source": TEMPORARY_AGENT_MANIFEST_SOURCE},
            )
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ALTER COLUMN manifest_source
                SET DEFAULT {_TEMPORARY_AGENT_MANIFEST_SOURCE_SQL}
                """
            )
            if agent_columns["manifest_source"].get("nullable", True):
                _ = connection.exec_driver_sql(
                    "ALTER TABLE agents ALTER COLUMN manifest_source SET NOT NULL"
                )

        if "manifest_hash" not in agent_columns:
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ADD COLUMN manifest_hash VARCHAR(64)
                NOT NULL DEFAULT {_TEMPORARY_AGENT_MANIFEST_HASH_SQL}
                """
            )
        else:
            _ = connection.execute(
                text(
                    """
                    UPDATE agents
                    SET manifest_hash = :manifest_hash
                    WHERE manifest_hash IS NULL
                    """
                ),
                {"manifest_hash": TEMPORARY_AGENT_MANIFEST_HASH},
            )
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ALTER COLUMN manifest_hash
                SET DEFAULT {_TEMPORARY_AGENT_MANIFEST_HASH_SQL}
                """
            )
            if agent_columns["manifest_hash"].get("nullable", True):
                _ = connection.exec_driver_sql(
                    "ALTER TABLE agents ALTER COLUMN manifest_hash SET NOT NULL"
                )

        if "compiler_version" not in agent_columns:
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ADD COLUMN compiler_version VARCHAR(80)
                NOT NULL DEFAULT {_AGENT_MANIFEST_COMPILER_VERSION_SQL}
                """
            )
        else:
            _ = connection.execute(
                text(
                    """
                    UPDATE agents
                    SET compiler_version = :compiler_version
                    WHERE compiler_version IS NULL
                    """
                ),
                {"compiler_version": AGENT_MANIFEST_COMPILER_VERSION},
            )
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE agents
                ALTER COLUMN compiler_version
                SET DEFAULT {_AGENT_MANIFEST_COMPILER_VERSION_SQL}
                """
            )
            if agent_columns["compiler_version"].get("nullable", True):
                _ = connection.exec_driver_sql(
                    "ALTER TABLE agents ALTER COLUMN compiler_version SET NOT NULL"
                )


def _ensure_workflow_manifest_columns(engine: Engine, table_names: set[str]) -> None:
    if "workflows" not in table_names:
        return

    inspector = inspect(engine)
    workflow_columns = {column["name"]: column for column in inspector.get_columns("workflows")}

    with engine.begin() as connection:
        if "manifest_api_version" not in workflow_columns:
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE workflows
                ADD COLUMN manifest_api_version VARCHAR(80)
                NOT NULL DEFAULT {_WORKFLOW_MANIFEST_API_VERSION_SQL}
                """
            )
        else:
            _ = connection.execute(
                text(
                    """
                    UPDATE workflows
                    SET manifest_api_version = :manifest_api_version
                    WHERE manifest_api_version IS NULL
                    """
                ),
                {"manifest_api_version": WORKFLOW_MANIFEST_API_VERSION},
            )
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE workflows
                ALTER COLUMN manifest_api_version
                SET DEFAULT {_WORKFLOW_MANIFEST_API_VERSION_SQL}
                """
            )
            if workflow_columns["manifest_api_version"].get("nullable", True):
                _ = connection.exec_driver_sql(
                    "ALTER TABLE workflows ALTER COLUMN manifest_api_version SET NOT NULL"
                )
        if "manifest_source" not in workflow_columns:
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE workflows
                ADD COLUMN manifest_source TEXT
                NOT NULL DEFAULT {_TEMPORARY_WORKFLOW_MANIFEST_SOURCE_SQL}
                """
            )
        else:
            _ = connection.execute(
                text(
                    """
                    UPDATE workflows
                    SET manifest_source = :manifest_source
                    WHERE manifest_source IS NULL
                    """
                ),
                {"manifest_source": TEMPORARY_WORKFLOW_MANIFEST_SOURCE},
            )
            _ = connection.exec_driver_sql(
                f"""
                ALTER TABLE workflows
                ALTER COLUMN manifest_source
                SET DEFAULT {_TEMPORARY_WORKFLOW_MANIFEST_SOURCE_SQL}
                """
            )
            if workflow_columns["manifest_source"].get("nullable", True):
                _ = connection.exec_driver_sql(
                    "ALTER TABLE workflows ALTER COLUMN manifest_source SET NOT NULL"
                )


def _remove_dead_agent_runtime_fields(engine: Engine, table_names: set[str]) -> None:
    if "agents" not in table_names:
        return

    inspector = inspect(engine)
    agent_columns = {column["name"] for column in inspector.get_columns("agents")}

    with engine.begin() as connection:
        if "temperature" in agent_columns:
            connection.exec_driver_sql(
                "ALTER TABLE agents DROP COLUMN IF EXISTS temperature CASCADE"
            )
        if "max_tool_rounds" in agent_columns:
            connection.exec_driver_sql(
                "ALTER TABLE agents DROP COLUMN IF EXISTS max_tool_rounds CASCADE"
            )
        if "streaming" in agent_columns:
            connection.exec_driver_sql("ALTER TABLE agents DROP COLUMN IF EXISTS streaming CASCADE")


def _remove_run_cost_columns(engine: Engine, table_names: set[str]) -> None:
    cost_word = "cost"
    currency_suffix = "usd"
    run_scopes = ("total", "inherited", "executed")
    run_column_names = tuple(f"{scope}_{cost_word}_{currency_suffix}" for scope in run_scopes)
    run_constraint_names = tuple(
        f"ck_runs_{scope}_{cost_word}_non_negative" for scope in run_scopes
    )
    invocation_column_name = f"{cost_word}_{currency_suffix}"
    invocation_constraint_name = f"ck_run_agent_invocations_{cost_word}_non_negative"

    inspector = inspect(engine)
    if "runs" in table_names:
        run_columns = {column["name"] for column in inspector.get_columns("runs")}
        run_constraints = {
            constraint["name"]
            for constraint in inspector.get_check_constraints("runs")
            if constraint.get("name")
        }
        with engine.begin() as connection:
            for constraint_name in run_constraint_names:
                if constraint_name in run_constraints:
                    _ = connection.exec_driver_sql(
                        f"ALTER TABLE runs DROP CONSTRAINT IF EXISTS {constraint_name}"
                    )
            for column_name in run_column_names:
                if column_name in run_columns:
                    _ = connection.exec_driver_sql(
                        f"ALTER TABLE runs DROP COLUMN IF EXISTS {column_name} CASCADE"
                    )

    if "run_agent_invocations" in table_names:
        invocation_columns = {
            column["name"] for column in inspector.get_columns("run_agent_invocations")
        }
        invocation_constraints = {
            constraint["name"]
            for constraint in inspector.get_check_constraints("run_agent_invocations")
            if constraint.get("name")
        }
        with engine.begin() as connection:
            if invocation_constraint_name in invocation_constraints:
                statement = (
                    "ALTER TABLE run_agent_invocations DROP CONSTRAINT IF EXISTS "
                    + invocation_constraint_name
                )
                _ = connection.exec_driver_sql(statement)
            if invocation_column_name in invocation_columns:
                statement = (
                    "ALTER TABLE run_agent_invocations DROP COLUMN IF EXISTS "
                    + f"{invocation_column_name} CASCADE"
                )
                _ = connection.exec_driver_sql(statement)


def _backfill_agent_model_connections(
    engine: Engine,
    table_names: set[str],
) -> None:
    if not {"agents", "model_connections"} <= table_names:
        return

    inspector = inspect(engine)
    agent_columns = {column["name"]: column for column in inspector.get_columns("agents")}
    if "model_connection_id" not in agent_columns or "model" not in agent_columns:
        return

    needs_non_null_enforcement = bool(agent_columns["model_connection_id"].get("nullable", True))

    with engine.begin() as connection:
        used_model_connection_keys = set(
            connection.execute(text("SELECT key FROM model_connections ORDER BY key ASC")).scalars()
        )
        unresolved_agent_count = connection.execute(
            text("SELECT COUNT(*) FROM agents WHERE model_connection_id IS NULL")
        ).scalar_one()
        if unresolved_agent_count == 0:
            if needs_non_null_enforcement:
                connection.exec_driver_sql(
                    "ALTER TABLE agents ALTER COLUMN model_connection_id SET NOT NULL"
                )
            return

        legacy_models = connection.execute(
            text(
                "SELECT DISTINCT BTRIM(model) AS model_id "
                "FROM agents "
                "WHERE model_connection_id IS NULL AND model IS NOT NULL AND BTRIM(model) <> '' "
                "ORDER BY model_id"
            )
        ).scalars()

        for legacy_model in legacy_models:
            placeholder_parameters = {
                "api_style": _MODEL_CONNECTION_DEFAULT_API_STYLE,
                "base_url": _MODEL_CONNECTION_PLACEHOLDER_BASE_URL,
                "model_id": legacy_model,
                "name": legacy_model,
                "reasoning_effort": _MODEL_CONNECTION_PLACEHOLDER_REASONING_EFFORT,
                "timeout_seconds": _MODEL_CONNECTION_PLACEHOLDER_TIMEOUT_SECONDS,
            }
            placeholder_connection_id = connection.execute(
                text(
                    "SELECT id FROM model_connections "
                    "WHERE status = 'active' "
                    "AND name = :name "
                    "AND model_id = :model_id "
                    "AND base_url = :base_url "
                    "AND reasoning_effort = :reasoning_effort "
                    "AND api_style = :api_style "
                    "AND timeout_seconds = :timeout_seconds "
                    "AND has_api_key = FALSE "
                    "ORDER BY id LIMIT 1"
                ),
                placeholder_parameters,
            ).scalar_one_or_none()

            if placeholder_connection_id is None:
                placeholder_parameters["key"] = build_unique_model_connection_key(
                    normalize_legacy_model_connection_key(
                        name=legacy_model,
                        model_id=legacy_model,
                    ),
                    used_model_connection_keys,
                )
                placeholder_connection_id = connection.execute(
                    text(
                        "INSERT INTO model_connections ("
                        "key, status, name, description, base_url, organization, project, "
                        "model_id, "
                        "reasoning_effort, api_style, timeout_seconds, "
                        "secret_payload, has_api_key, created_at, updated_at"
                        ") VALUES ("
                        ":key, 'active', :name, '', :base_url, NULL, NULL, :model_id, "
                        ":reasoning_effort, :api_style, :timeout_seconds, '{}'::jsonb, FALSE, "
                        "NOW(), NOW()"
                        ") RETURNING id"
                    ),
                    placeholder_parameters,
                ).scalar_one()

            connection.execute(
                text(
                    "UPDATE agents "
                    "SET model_connection_id = :model_connection_id, updated_at = NOW() "
                    "WHERE model_connection_id IS NULL AND BTRIM(model) = :legacy_model"
                ),
                {
                    "legacy_model": legacy_model,
                    "model_connection_id": placeholder_connection_id,
                },
            )

        remaining_null_count = connection.execute(
            text("SELECT COUNT(*) FROM agents WHERE model_connection_id IS NULL")
        ).scalar_one()
        if needs_non_null_enforcement and remaining_null_count == 0:
            connection.exec_driver_sql(
                "ALTER TABLE agents ALTER COLUMN model_connection_id SET NOT NULL"
            )


def _ensure_run_lifecycle_support(engine: Engine, table_names: set[str]) -> None:
    if "runs" not in table_names:
        return

    inspector = inspect(engine)
    run_columns = {column["name"]: column for column in inspector.get_columns("runs")}
    run_checks = {
        constraint["name"]
        for constraint in inspector.get_check_constraints("runs")
        if constraint.get("name")
    }

    with engine.begin() as connection:
        if "queued_at" not in run_columns:
            connection.exec_driver_sql("ALTER TABLE runs ADD COLUMN queued_at TIMESTAMPTZ")
            connection.execute(
                text(
                    """
                    UPDATE runs
                    SET queued_at = COALESCE(created_at, started_at, NOW())
                    WHERE queued_at IS NULL
                    """
                )
            )
            connection.exec_driver_sql("ALTER TABLE runs ALTER COLUMN queued_at SET NOT NULL")
            connection.exec_driver_sql("ALTER TABLE runs ALTER COLUMN queued_at SET DEFAULT NOW()")
        else:
            connection.execute(
                text(
                    """
                    UPDATE runs
                    SET queued_at = COALESCE(created_at, started_at, NOW())
                    WHERE queued_at IS NULL
                    """
                )
            )
            queued_at_column = run_columns["queued_at"]
            if queued_at_column.get("nullable", True):
                connection.exec_driver_sql("ALTER TABLE runs ALTER COLUMN queued_at SET NOT NULL")
            connection.exec_driver_sql("ALTER TABLE runs ALTER COLUMN queued_at SET DEFAULT NOW()")
        if "started_at" in run_columns:
            started_at_column = run_columns["started_at"]
            if not started_at_column.get("nullable", True):
                connection.exec_driver_sql("ALTER TABLE runs ALTER COLUMN started_at DROP NOT NULL")
            connection.exec_driver_sql("ALTER TABLE runs ALTER COLUMN started_at DROP DEFAULT")
        else:
            connection.exec_driver_sql("ALTER TABLE runs ADD COLUMN started_at TIMESTAMPTZ")
        connection.exec_driver_sql("ALTER TABLE runs ALTER COLUMN status SET DEFAULT 'queued'")
        if "ck_runs_status" in run_checks:
            connection.exec_driver_sql("ALTER TABLE runs DROP CONSTRAINT ck_runs_status")
        connection.exec_driver_sql(
            "ALTER TABLE runs ADD CONSTRAINT ck_runs_status "
            "CHECK (status IN ('queued', 'running', 'succeeded', 'failed'))"
        )


def _ensure_run_graph_metadata_support(engine: Engine, table_names: set[str]) -> None:
    inspector = inspect(engine)
    with engine.begin() as connection:
        if "run_steps" in table_names:
            run_step_columns = {column["name"] for column in inspector.get_columns("run_steps")}
            if "graph_metadata" not in run_step_columns:
                connection.exec_driver_sql("ALTER TABLE run_steps ADD COLUMN graph_metadata JSONB")
        if "run_agent_invocations" in table_names:
            invocation_columns = {
                column["name"] for column in inspector.get_columns("run_agent_invocations")
            }
            if "graph_metadata" not in invocation_columns:
                connection.exec_driver_sql(
                    "ALTER TABLE run_agent_invocations ADD COLUMN graph_metadata JSONB"
                )


def _recover_stale_agent_platform_runs(engine: Engine, table_names: set[str]) -> None:
    if "runs" not in table_names:
        return

    with engine.begin() as connection:
        connection.execute(
            text(
                """
                UPDATE runs
                SET status = 'failed',
                    error = COALESCE(NULLIF(error, ''), :restart_failure_message),
                    finished_at = COALESCE(finished_at, NOW()),
                    updated_at = NOW()
                WHERE status = 'running'
                """
            ),
            {"restart_failure_message": _AGENT_PLATFORM_RESTART_FAILURE_MESSAGE},
        )
        if "run_steps" in table_names:
            connection.execute(
                text(
                    """
                    UPDATE run_steps
                    SET status = 'failed',
                        error = COALESCE(NULLIF(error, ''), :restart_failure_message),
                        finished_at = COALESCE(finished_at, NOW()),
                        updated_at = NOW()
                    WHERE status = 'running'
                    """
                ),
                {"restart_failure_message": _AGENT_PLATFORM_RESTART_FAILURE_MESSAGE},
            )
            connection.execute(
                text(
                    """
                    UPDATE run_steps AS step
                    SET status = 'skipped',
                        error = COALESCE(NULLIF(step.error, ''), :pending_skip_message),
                        finished_at = COALESCE(step.finished_at, NOW()),
                        updated_at = NOW()
                    FROM runs AS run
                    WHERE step.run_id = run.id
                      AND run.status = 'failed'
                      AND step.status = 'pending'
                    """
                ),
                {"pending_skip_message": _AGENT_PLATFORM_PENDING_SKIP_MESSAGE},
            )
        if "run_agent_invocations" in table_names:
            connection.execute(
                text(
                    """
                    UPDATE run_agent_invocations
                    SET status = 'failed',
                        error_code = COALESCE(NULLIF(error_code, ''), 'startup_recovery'),
                        error_message = COALESCE(
                            NULLIF(error_message, ''),
                            :restart_failure_message
                        ),
                        finished_at = COALESCE(finished_at, NOW()),
                        updated_at = NOW()
                    WHERE status = 'running'
                    """
                ),
                {"restart_failure_message": _AGENT_PLATFORM_RESTART_FAILURE_MESSAGE},
            )
            connection.execute(
                text(
                    """
                    UPDATE run_agent_invocations AS invocation
                    SET status = 'skipped',
                        error_code = COALESCE(
                            NULLIF(invocation.error_code, ''),
                            'startup_recovery'
                        ),
                        error_message = COALESCE(
                            NULLIF(invocation.error_message, ''),
                            :pending_skip_message
                        ),
                        finished_at = COALESCE(invocation.finished_at, NOW()),
                        updated_at = NOW()
                    FROM runs AS run
                    WHERE invocation.run_id = run.id
                      AND run.status = 'failed'
                      AND invocation.status = 'pending'
                    """
                ),
                {"pending_skip_message": _AGENT_PLATFORM_PENDING_SKIP_MESSAGE},
            )


def _reset_legacy_mcp_server_table(engine: Engine, table_names: set[str]) -> None:
    if "mcp_servers" not in table_names:
        return

    inspector = inspect(engine)
    mcp_columns = {column["name"] for column in inspector.get_columns("mcp_servers")}
    expected_columns = {"id", "key", "version", "status", "config", "created_at", "updated_at"}
    if mcp_columns == expected_columns:
        return

    if "config" in mcp_columns and not (
        {"transport", "command", "url", "auth", "enabled"} & mcp_columns
    ):
        return

    statements = dict(_AGENT_PLATFORM_TABLE_STATEMENTS)["mcp_servers"]
    with engine.begin() as connection:
        connection.exec_driver_sql('DROP TABLE IF EXISTS "mcp_servers" CASCADE')
        for statement in statements:
            connection.exec_driver_sql(statement)
    table_names.add("mcp_servers")


def _flatten_legacy_mcp_server_rows(engine: Engine, table_names: set[str]) -> None:
    if "mcp_servers" not in table_names:
        return

    with engine.begin() as connection:
        legacy_rows = connection.exec_driver_sql(
            "SELECT id, key, config FROM mcp_servers ORDER BY id"
        ).all()
        for server_id, key, config in legacy_rows:
            flattened_payload = flatten_mcp_server_storage_payload(config, key=str(key))
            if flattened_payload is None:
                continue

            next_payload, changed = flattened_payload
            if not changed:
                continue

            connection.execute(
                text(
                    "UPDATE mcp_servers "
                    "SET config = CAST(:config AS jsonb), updated_at = NOW() "
                    "WHERE id = :server_id"
                ),
                {
                    "config": json.dumps(next_payload, sort_keys=True, separators=(",", ":")),
                    "server_id": server_id,
                },
            )


def _sanitize_retired_stock_analysis_resources(engine: Engine, table_names: set[str]) -> None:
    del engine, table_names


def _drop_tables(engine: Engine, table_names: set[str], tables: tuple[str, ...]) -> None:
    with engine.begin() as connection:
        for table_name in tables:
            if table_name not in table_names:
                continue
            connection.exec_driver_sql(f'DROP TABLE IF EXISTS "{table_name}" CASCADE')
            table_names.discard(table_name)


def _repair_legacy_agent_memory_report_sources(engine: Engine, table_names: set[str]) -> None:
    if "reports" not in table_names:
        return

    with engine.begin() as connection:
        connection.execute(
            text(
                """
                UPDATE reports
                SET source = 'agent',
                    metadata = jsonb_set(
                        metadata,
                        '{createdBy}',
                        jsonb_strip_nulls(
                            jsonb_build_object(
                                'type', 'agent',
                                'runId', (metadata->'analysis'->>'runId')::int,
                                'agentKey', metadata->'analysis'->'agentKey',
                                'agentVersion', (metadata->'analysis'->>'agentVersion')::int,
                                'agentName', metadata->'analysis'->'agentName',
                                'workflowKey', metadata->'analysis'->'workflowKey',
                                'workflowVersion', metadata->'analysis'->'workflowVersion',
                                'stepId', metadata->'analysis'->'stepId',
                                'slot', metadata->'analysis'->'slot',
                                'traceId', metadata->'analysis'->'traceId'
                            )
                        ),
                        true
                    ),
                    updated_at = NOW()
                WHERE source = 'external'
                  AND jsonb_typeof(metadata) = 'object'
                  AND jsonb_typeof(metadata->'analysis') = 'object'
                  AND metadata->'analysis'->>'reviewType' = 'agent_memory'
                  AND metadata->'analysis'->>'versionGroup' = 'agent_memory/v1'
                  AND btrim(COALESCE(metadata->'analysis'->>'agentKey', '')) <> ''
                  AND (metadata->'analysis'->>'agentVersion') ~ '^[0-9]+$'
                  AND (metadata->'analysis'->>'runId') ~ '^[0-9]+$'
                """
            )
        )


def upgrade_legacy_schema(engine: Engine) -> None:
    validate_supported_database_engine(engine)
    inspector = inspect(engine)
    table_names = set(inspector.get_table_names())

    hard_cutover_required = _agent_platform_hard_cutover_required(engine, table_names)
    _cutover_capability_storage(engine, table_names)
    if hard_cutover_required:
        _reset_agent_platform_runtime_tables(engine, table_names)
    _ensure_agent_platform_tables(engine, table_names)
    _remove_run_cost_columns(engine, table_names)
    if not hard_cutover_required and _agent_platform_hard_cutover_required(engine, table_names):
        _reset_agent_platform_runtime_tables(engine, table_names)
        _ensure_agent_platform_tables(engine, table_names)
        _remove_run_cost_columns(engine, table_names)
    _ensure_model_connection_key_support(engine, table_names)
    _ensure_model_connection_reasoning_effort_support(engine, table_names)
    _ensure_model_connection_api_style_support(engine, table_names)
    _ensure_agent_manifest_columns(engine, table_names)
    _ensure_workflow_manifest_columns(engine, table_names)
    _remove_dead_agent_runtime_fields(engine, table_names)
    _ensure_agent_model_connection_support(engine, table_names)
    _backfill_agent_model_connections(
        engine,
        table_names,
    )
    _ensure_agent_model_connection_snapshot_support(engine, table_names)
    _reset_legacy_mcp_server_table(engine, table_names)
    _flatten_legacy_mcp_server_rows(engine, table_names)
    _ensure_run_lifecycle_support(engine, table_names)
    _ensure_run_graph_metadata_support(engine, table_names)
    _recover_stale_agent_platform_runs(engine, table_names)

    if "portfolios" in table_names:
        portfolio_columns = {column["name"] for column in inspector.get_columns("portfolios")}
        if "slug" not in portfolio_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql("ALTER TABLE portfolios ADD COLUMN slug VARCHAR(100)")
                legacy_portfolios = connection.exec_driver_sql(
                    "SELECT id, name FROM portfolios ORDER BY id"
                ).all()
                used_slugs: set[str] = set()
                for portfolio_id, name in legacy_portfolios:
                    connection.execute(
                        text("UPDATE portfolios SET slug = :slug WHERE id = :portfolio_id"),
                        {
                            "slug": build_unique_legacy_portfolio_slug(
                                normalize_legacy_portfolio_slug(name), used_slugs
                            ),
                            "portfolio_id": portfolio_id,
                        },
                    )
                connection.exec_driver_sql("ALTER TABLE portfolios ALTER COLUMN slug SET NOT NULL")
                connection.exec_driver_sql(
                    "ALTER TABLE portfolios ADD CONSTRAINT uq_portfolios_slug UNIQUE (slug)"
                )

    if "balances" in table_names:
        balance_columns = {column["name"] for column in inspector.get_columns("balances")}
        if "operation_type" not in balance_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql("ALTER TABLE balances ADD COLUMN operation_type VARCHAR")
                connection.exec_driver_sql(
                    "UPDATE balances SET operation_type = 'DEPOSIT' WHERE operation_type IS NULL"
                )
                connection.exec_driver_sql(
                    "ALTER TABLE balances ALTER COLUMN operation_type SET NOT NULL"
                )

    if "reports" in table_names:
        report_columns = {column["name"] for column in inspector.get_columns("reports")}
        if "slug" not in report_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql("ALTER TABLE reports ADD COLUMN slug VARCHAR(200)")
                connection.exec_driver_sql("UPDATE reports SET slug = name WHERE slug IS NULL")
                connection.exec_driver_sql("ALTER TABLE reports ALTER COLUMN slug SET NOT NULL")
                connection.exec_driver_sql(
                    "ALTER TABLE reports ADD CONSTRAINT uq_reports_slug UNIQUE (slug)"
                )
        if "source" not in report_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql(
                    "ALTER TABLE reports ADD COLUMN source VARCHAR(20) DEFAULT 'compiled' NOT NULL"
                )
        if "metadata" not in report_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql(
                    "ALTER TABLE reports ADD COLUMN metadata JSONB DEFAULT '{}' NOT NULL"
                )
        _repair_legacy_agent_memory_report_sources(engine, table_names)

    if "market_quotes" in table_names:
        market_quote_columns = {column["name"] for column in inspector.get_columns("market_quotes")}
        if "name" not in market_quote_columns:
            with engine.begin() as connection:
                connection.exec_driver_sql("ALTER TABLE market_quotes ADD COLUMN name VARCHAR(255)")

    _sanitize_retired_stock_analysis_resources(engine, table_names)
    _drop_tables(engine, table_names, _LEGACY_BACKEND_TABLES)
    _drop_tables(engine, table_names, _OBSOLETE_TABLES)
