"""Bundled Digital Oracle Runtime extension."""

from __future__ import annotations

from app.extensions.contract import Extension

from .ownership import (
    DIGITAL_ORACLE_DENIED_CODE,
    DIGITAL_ORACLE_DENIED_MESSAGES,
    DIGITAL_ORACLE_EXTENSION_KEY,
    DIGITAL_ORACLE_OPENAI_FUNCTION_NAMES,
    DIGITAL_ORACLE_RUNTIME_TOOL_KEYS,
)
from .runtime_executors import DIGITAL_ORACLE_RUNTIME_TOOL_SPECS
from .tool_specs import DIGITAL_ORACLE_SERVER_DECLARED_TOOL_SPECS

EXTENSION = Extension(
    key=DIGITAL_ORACLE_EXTENSION_KEY,
    tool_declarations=DIGITAL_ORACLE_SERVER_DECLARED_TOOL_SPECS,
    runtime_tool_specs=DIGITAL_ORACLE_RUNTIME_TOOL_SPECS,
)

__all__ = [
    "EXTENSION",
    "DIGITAL_ORACLE_DENIED_CODE",
    "DIGITAL_ORACLE_DENIED_MESSAGES",
    "DIGITAL_ORACLE_EXTENSION_KEY",
    "DIGITAL_ORACLE_OPENAI_FUNCTION_NAMES",
    "DIGITAL_ORACLE_RUNTIME_TOOL_KEYS",
]
