from __future__ import annotations

from collections.abc import Sequence

from sqlalchemy.orm import Session

from app.agents import get_default_tool_catalog
from app.extensions.signaldeck_finance.ownership import (
    FINANCE_WORKSPACE_DENIED_CODE,
    FINANCE_WORKSPACE_DENIED_MESSAGES,
)
from app.extensions.signaldeck_finance.runtime_types import (
    MARKET_DATA_HISTORY_LOOKUP_TOOL_KEY,
    MARKET_DATA_QUOTE_LOOKUP_TOOL_KEY,
    POSITION_LOOKUP_TOOL_KEY,
    REPORT_LOOKUP_TOOL_KEY,
)
from app.services.capability_service import CapabilityService, RuntimeToolGrantPolicy

REPORT_LOOKUP_ACCESS_DENIED_CODE = FINANCE_WORKSPACE_DENIED_CODE
POSITION_LOOKUP_ACCESS_DENIED_CODE = FINANCE_WORKSPACE_DENIED_CODE
MARKET_DATA_QUOTE_LOOKUP_ACCESS_DENIED_CODE = FINANCE_WORKSPACE_DENIED_CODE
MARKET_DATA_HISTORY_LOOKUP_ACCESS_DENIED_CODE = FINANCE_WORKSPACE_DENIED_CODE

REPORT_LOOKUP_ACCESS_DENIED_MESSAGE = FINANCE_WORKSPACE_DENIED_MESSAGES[REPORT_LOOKUP_TOOL_KEY]
POSITION_LOOKUP_ACCESS_DENIED_MESSAGE = FINANCE_WORKSPACE_DENIED_MESSAGES[POSITION_LOOKUP_TOOL_KEY]
MARKET_DATA_QUOTE_LOOKUP_ACCESS_DENIED_MESSAGE = FINANCE_WORKSPACE_DENIED_MESSAGES[
    MARKET_DATA_QUOTE_LOOKUP_TOOL_KEY
]
MARKET_DATA_HISTORY_LOOKUP_ACCESS_DENIED_MESSAGE = FINANCE_WORKSPACE_DENIED_MESSAGES[
    MARKET_DATA_HISTORY_LOOKUP_TOOL_KEY
]

REPORT_LOOKUP_GRANT_POLICY = RuntimeToolGrantPolicy(
    tool_key=REPORT_LOOKUP_TOOL_KEY,
    denied_code=REPORT_LOOKUP_ACCESS_DENIED_CODE,
    denied_message=REPORT_LOOKUP_ACCESS_DENIED_MESSAGE,
)
POSITION_LOOKUP_GRANT_POLICY = RuntimeToolGrantPolicy(
    tool_key=POSITION_LOOKUP_TOOL_KEY,
    denied_code=POSITION_LOOKUP_ACCESS_DENIED_CODE,
    denied_message=POSITION_LOOKUP_ACCESS_DENIED_MESSAGE,
)
MARKET_DATA_QUOTE_LOOKUP_GRANT_POLICY = RuntimeToolGrantPolicy(
    tool_key=MARKET_DATA_QUOTE_LOOKUP_TOOL_KEY,
    denied_code=MARKET_DATA_QUOTE_LOOKUP_ACCESS_DENIED_CODE,
    denied_message=MARKET_DATA_QUOTE_LOOKUP_ACCESS_DENIED_MESSAGE,
)
MARKET_DATA_HISTORY_LOOKUP_GRANT_POLICY = RuntimeToolGrantPolicy(
    tool_key=MARKET_DATA_HISTORY_LOOKUP_TOOL_KEY,
    denied_code=MARKET_DATA_HISTORY_LOOKUP_ACCESS_DENIED_CODE,
    denied_message=MARKET_DATA_HISTORY_LOOKUP_ACCESS_DENIED_MESSAGE,
)


def require_finance_runtime_tool_grant(
    session: Session,
    *,
    capability_references: Sequence[dict[str, object]],
    grant_policy: RuntimeToolGrantPolicy,
) -> None:
    CapabilityService(session, get_default_tool_catalog()).require_runtime_tool_grant(
        capability_references=capability_references,
        grant_policy=grant_policy,
    )


__all__ = [
    "MARKET_DATA_HISTORY_LOOKUP_ACCESS_DENIED_CODE",
    "MARKET_DATA_HISTORY_LOOKUP_ACCESS_DENIED_MESSAGE",
    "MARKET_DATA_HISTORY_LOOKUP_GRANT_POLICY",
    "MARKET_DATA_QUOTE_LOOKUP_ACCESS_DENIED_CODE",
    "MARKET_DATA_QUOTE_LOOKUP_ACCESS_DENIED_MESSAGE",
    "MARKET_DATA_QUOTE_LOOKUP_GRANT_POLICY",
    "POSITION_LOOKUP_ACCESS_DENIED_CODE",
    "POSITION_LOOKUP_ACCESS_DENIED_MESSAGE",
    "POSITION_LOOKUP_GRANT_POLICY",
    "REPORT_LOOKUP_ACCESS_DENIED_CODE",
    "REPORT_LOOKUP_ACCESS_DENIED_MESSAGE",
    "REPORT_LOOKUP_GRANT_POLICY",
    "require_finance_runtime_tool_grant",
]
